// Transforms the compodoc `documentation.json` into a trimmed, typed API
// dataset the website renders as each component's reference table. Run after
// compodoc via the `docs:api` script; not meant to be invoked on its own.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const DOC_JSON = resolve(here, '../dist/compodoc/documentation.json');
const OUT_FILE = resolve(here, '../../../apps/website/src/app/data/ui-api.generated.ts');

function stripHtml(html) {
  return (html ?? '')
    .replace(/<[^>]+>/g, '')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\s+/g, ' ')
    .trim();
}

function slugFromSelector(selector) {
  return (selector ?? '').replace(/[[\]]/g, '').replace(/^ea-/, '');
}

// Inputs that default to a generated value (random id, timestamp) expose the
// raw expression as their default; surface a readable placeholder instead.
function cleanDefault(raw) {
  const value = (raw ?? '').trim();
  if (/uniqueId|Math\.random|crypto\.|Date\.now|\$\{/.test(value)) {
    return '(auto-generated)';
  }
  return value;
}

function toInput(prop, twoWay) {
  return {
    name: prop.name,
    type: prop.type || 'unknown',
    default: cleanDefault(prop.defaultValue),
    required: !!prop.required,
    twoWay,
    description: stripHtml(prop.description),
  };
}

function toMethod(method) {
  const args = (method.args ?? [])
    .map(a => `${a.name}${a.optional ? '?' : ''}: ${a.type || 'unknown'}`)
    .join(', ');
  return {
    name: method.name,
    signature: `${method.name}(${args}): ${method.returnType || 'void'}`,
    description: stripHtml(method.description),
  };
}

function buildEntry(entity) {
  const inputs = entity.inputsClass ?? [];
  const outputs = entity.outputsClass ?? [];
  const inputNames = new Set(inputs.map(i => i.name));

  return {
    selector: entity.selector ?? '',
    // A `model()` surfaces in both inputs and outputs; show it once, on the
    // input row, flagged two-way, rather than duplicating it under outputs.
    inputs: inputs.map(i =>
      toInput(
        i,
        outputs.some(o => o.name === i.name),
      ),
    ),
    outputs: outputs.filter(o => !inputNames.has(o.name)).map(o => toInput(o, false)),
    // Only methods with a doc comment are part of the intended public API;
    // CVA hooks and internal handlers are left undocumented and so excluded.
    methods: (entity.methodsClass ?? [])
      .filter(m => stripHtml(m.description))
      .map(toMethod),
  };
}

const doc = JSON.parse(readFileSync(DOC_JSON, 'utf8'));
const entities = [...(doc.components ?? []), ...(doc.directives ?? [])];

const api = {};
for (const entity of entities) {
  const slug = slugFromSelector(entity.selector);
  if (slug) {
    api[slug] = buildEntry(entity);
  }
}

const sorted = Object.fromEntries(
  Object.keys(api)
    .sort()
    .map(k => [k, api[k]]),
);

const banner = `// AUTO-GENERATED by packages/ui/scripts/extract-api.mjs — do not edit by hand.
// Regenerate with: pnpm --filter @eagami/ui docs:api
`;

const types = `export interface ApiProp {
  // Index signature lets rows satisfy ea-data-table's Record<string, unknown> generic.
  [key: string]: unknown;
  name: string;
  type: string;
  default: string;
  required: boolean;
  twoWay: boolean;
  description: string;
}

export interface ApiMethod {
  [key: string]: unknown;
  name: string;
  signature: string;
  description: string;
}

export interface ComponentApi {
  selector: string;
  inputs: ApiProp[];
  outputs: ApiProp[];
  methods: ApiMethod[];
}
`;

const body = `export const UI_API: Readonly<Record<string, ComponentApi>> = ${JSON.stringify(sorted, null, 2)};
`;

writeFileSync(OUT_FILE, `${banner}\n${types}\n${body}`);
console.log(`Wrote ${Object.keys(sorted).length} component API entries to ${OUT_FILE}`);
