import {
  ActivityIconComponent,
  AirplayIconComponent,
  AlertCircleIconComponent,
  AlertOctagonIconComponent,
  AlertTriangleIconComponent,
  AlignCenterIconComponent,
  AlignJustifyIconComponent,
  AlignLeftIconComponent,
  AlignRightIconComponent,
  AnchorIconComponent,
  ApertureIconComponent,
  ArchiveIconComponent,
  ArrowDownIconComponent,
  ArrowDownLeftIconComponent,
  ArrowDownRightIconComponent,
  ArrowLeftIconComponent,
  ArrowRightIconComponent,
  ArrowUpIconComponent,
  ArrowUpLeftIconComponent,
  ArrowUpRightIconComponent,
  AtSignIconComponent,
  AwardIconComponent,
  BarChartIconComponent,
  BatteryChargingIconComponent,
  BatteryIconComponent,
  BellIconComponent,
  BellOffIconComponent,
  BluetoothIconComponent,
  BoldIconComponent,
  BookIconComponent,
  BookOpenIconComponent,
  BookmarkIconComponent,
  BottleIconComponent,
  BoxIconComponent,
  BriefcaseIconComponent,
  CalendarIconComponent,
  CameraIconComponent,
  CandleIconComponent,
  CheckCircleIconComponent,
  CheckIconComponent,
  ChevronDownIconComponent,
  ChevronLeftIconComponent,
  ChevronRightIconComponent,
  ChevronUpIconComponent,
  ChevronsUpDownIconComponent,
  ChromeIconComponent,
  CircleIconComponent,
  ClipboardIconComponent,
  ClockIconComponent,
  CloudIconComponent,
  CloudflareIconComponent,
  CodeIconComponent,
  CodepenIconComponent,
  CodesandboxIconComponent,
  CoffeeIconComponent,
  ColumnsIconComponent,
  CommandIconComponent,
  CompassIconComponent,
  CopyIconComponent,
  CornerDownLeftIconComponent,
  CornerDownRightIconComponent,
  CornerUpLeftIconComponent,
  CornerUpRightIconComponent,
  CpuIconComponent,
  CreditCardIconComponent,
  CropIconComponent,
  CrosshairIconComponent,
  DatabaseIconComponent,
  DeleteIconComponent,
  DiscIconComponent,
  DiscordIconComponent,
  DivideIconComponent,
  DockerIconComponent,
  DollarSignIconComponent,
  DownloadCloudIconComponent,
  DownloadIconComponent,
  DropboxIconComponent,
  DropletIconComponent,
  EagamiIconComponent,
  Edit2IconComponent,
  Edit3IconComponent,
  EditIconComponent,
  ExternalLinkIconComponent,
  EyeIconComponent,
  EyeOffIconComponent,
  FacebookIconComponent,
  FastForwardIconComponent,
  FeatherIconComponent,
  FigmaIconComponent,
  FileIconComponent,
  FileMinusIconComponent,
  FilePlusIconComponent,
  FileTextIconComponent,
  FilmIconComponent,
  FilterIconComponent,
  FlagIconComponent,
  FolderIconComponent,
  FrownIconComponent,
  GiftIconComponent,
  GitBranchIconComponent,
  GitCommitIconComponent,
  GitMergeIconComponent,
  GitPullRequestIconComponent,
  GithubIconComponent,
  GitlabIconComponent,
  GlobeIconComponent,
  GoogleIconComponent,
  GridIconComponent,
  HardDriveIconComponent,
  HashIconComponent,
  HeadphonesIconComponent,
  HeartIconComponent,
  HelpCircleIconComponent,
  HeptagonIconComponent,
  HexagonIconComponent,
  HomeIconComponent,
  ImageIconComponent,
  InboxIconComponent,
  InfoIconComponent,
  ItalicIconComponent,
  KeyIconComponent,
  KubernetesIconComponent,
  LampIconComponent,
  LayersIconComponent,
  LayoutIconComponent,
  LifeBuoyIconComponent,
  Link2IconComponent,
  LinkIconComponent,
  LinkedinIconComponent,
  ListIconComponent,
  LoaderIconComponent,
  LockIconComponent,
  LogInIconComponent,
  LogOutIconComponent,
  MailIconComponent,
  MapIconComponent,
  MapPinIconComponent,
  MastercardIconComponent,
  Maximize2IconComponent,
  MaximizeIconComponent,
  MehIconComponent,
  MenuIconComponent,
  MessageCircleIconComponent,
  MessageSquareIconComponent,
  MicIconComponent,
  MicOffIconComponent,
  MicrosoftIconComponent,
  Minimize2IconComponent,
  MinimizeIconComponent,
  MinusCircleIconComponent,
  MinusIconComponent,
  MinusSquareIconComponent,
  MongodbIconComponent,
  MonitorIconComponent,
  MoonIconComponent,
  MoreHorizontalIconComponent,
  MoreVerticalIconComponent,
  MousePointerIconComponent,
  MoveIconComponent,
  MusicIconComponent,
  Navigation2IconComponent,
  NavigationIconComponent,
  NetlifyIconComponent,
  NotionIconComponent,
  NpmIconComponent,
  OctagonIconComponent,
  PackageIconComponent,
  PaperclipIconComponent,
  PauseCircleIconComponent,
  PauseIconComponent,
  PaypalIconComponent,
  PencilIconComponent,
  PentagonIconComponent,
  PercentIconComponent,
  PhoneIconComponent,
  PieChartIconComponent,
  PlayCircleIconComponent,
  PlayIconComponent,
  PlusCircleIconComponent,
  PlusIconComponent,
  PlusSquareIconComponent,
  PocketIconComponent,
  PowerIconComponent,
  PrinterIconComponent,
  RadioIconComponent,
  RectangleHorizontalIconComponent,
  RectangleVerticalIconComponent,
  RedditIconComponent,
  RefreshCwIconComponent,
  RepeatIconComponent,
  RewindIconComponent,
  RotateCcwIconComponent,
  RotateCwIconComponent,
  RssIconComponent,
  SaveIconComponent,
  ScissorsIconComponent,
  SearchIconComponent,
  SendIconComponent,
  ServerIconComponent,
  SettingsIconComponent,
  Share2IconComponent,
  ShareIconComponent,
  ShieldIconComponent,
  ShieldOffIconComponent,
  ShoppingBagIconComponent,
  ShoppingCartIconComponent,
  ShuffleIconComponent,
  SidebarIconComponent,
  SkipBackIconComponent,
  SkipForwardIconComponent,
  SlackIconComponent,
  SlashIconComponent,
  SlidersIconComponent,
  SmartphoneIconComponent,
  SmileIconComponent,
  SoccerBallIconComponent,
  SpeakerIconComponent,
  SpotifyIconComponent,
  SquareIconComponent,
  StarIconComponent,
  StopCircleIconComponent,
  StripeIconComponent,
  SunIconComponent,
  SunriseIconComponent,
  SunsetIconComponent,
  TabletIconComponent,
  TagIconComponent,
  TargetIconComponent,
  TerminalIconComponent,
  ThermometerIconComponent,
  ThumbsDownIconComponent,
  ThumbsUpIconComponent,
  ToggleLeftIconComponent,
  ToggleRightIconComponent,
  ToolIconComponent,
  Trash2IconComponent,
  TrashIconComponent,
  TrendingDownIconComponent,
  TrendingUpIconComponent,
  TriangleIconComponent,
  TrophyIconComponent,
  TruckIconComponent,
  TvIconComponent,
  TwitchIconComponent,
  TypeIconComponent,
  UmbrellaIconComponent,
  UnderlineIconComponent,
  UnlockIconComponent,
  UploadCloudIconComponent,
  UploadIconComponent,
  UserCheckIconComponent,
  UserIconComponent,
  UserMinusIconComponent,
  UserPlusIconComponent,
  UserXIconComponent,
  UsersIconComponent,
  VercelIconComponent,
  VideoIconComponent,
  VideoOffIconComponent,
  VoicemailIconComponent,
  Volume1IconComponent,
  Volume2IconComponent,
  VolumeIconComponent,
  VolumeXIconComponent,
  WatchIconComponent,
  WifiIconComponent,
  WifiOffIconComponent,
  WindIconComponent,
  XCircleIconComponent,
  XIconComponent,
  XOctagonIconComponent,
  XSquareIconComponent,
  XTwitterIconComponent,
  YoutubeIconComponent,
  ZapIconComponent,
  ZapOffIconComponent,
  ZoomInIconComponent,
  ZoomOutIconComponent,
} from '@eagami/ui';

import { Type } from '@angular/core';

/**
 * Each icon ships with a multilingual tag list so the /ui/icons filter input
 * matches user-typed terms in any of the site's supported locales. Tags are
 * deliberately not split per locale (one combined array per icon) so a single
 * search field works for everyone without a per-locale tag map to maintain.
 */
export type IconCategory = 'feather' | 'eagami' | 'brand';

export interface IconEntry {
  readonly slug: string;
  readonly component: Type<unknown>;
  readonly categories: ReadonlyArray<IconCategory>;
  readonly tags: ReadonlyArray<string>;
}

export const ICONS: ReadonlyArray<IconEntry> = [
  {
    slug: 'activity',
    component: ActivityIconComponent,
    categories: ['feather'],
    tags: [
      'activity',
      'pulse',
      'heartbeat',
      'health',
      'fitness',
      'activité',
      'pouls',
      'actividad',
      'pulso',
      'δραστηριότητα',
      'παλμός',
      'aktywność',
      'puls',
    ],
  },
  {
    slug: 'airplay',
    component: AirplayIconComponent,
    categories: ['feather'],
    tags: [
      'airplay',
      'cast',
      'stream',
      'mirror',
      'screen',
      'diffusion',
      'transmisión',
      'μετάδοση',
      'transmisja',
    ],
  },
  {
    slug: 'alert-circle',
    component: AlertCircleIconComponent,
    categories: ['feather'],
    tags: [
      'alert-circle',
      'alert',
      'circle',
      'warning',
      'caution',
      'notification',
      'alerte',
      'avertissement',
      'alerta',
      'aviso',
      'ειδοποίηση',
      'προσοχή',
      'alarm',
      'ostrzeżenie',
    ],
  },
  {
    slug: 'alert-octagon',
    component: AlertOctagonIconComponent,
    categories: ['feather'],
    tags: [
      'alert-octagon',
      'alert',
      'octagon',
      'warning',
      'stop',
      'danger',
      'alerte',
      'octogone',
      'alerta',
      'octágono',
      'ειδοποίηση',
      'οκτάγωνο',
      'alarm',
      'ostrzeżenie',
    ],
  },
  {
    slug: 'alert-triangle',
    component: AlertTriangleIconComponent,
    categories: ['feather'],
    tags: [
      'alert-triangle',
      'alert',
      'triangle',
      'warning',
      'caution',
      'danger',
      'alerte',
      'triángulo',
      'alerta',
      'ειδοποίηση',
      'τρίγωνο',
      'alarm',
      'ostrzeżenie',
    ],
  },
  {
    slug: 'align-center',
    component: AlignCenterIconComponent,
    categories: ['feather'],
    tags: [
      'align-center',
      'align',
      'center',
      'centre',
      'text',
      'format',
      'paragraph',
      'centrer',
      'centrado',
      'στοίχιση',
      'κέντρο',
      'wyśrodkuj',
      'środek',
    ],
  },
  {
    slug: 'align-justify',
    component: AlignJustifyIconComponent,
    categories: ['feather'],
    tags: [
      'align-justify',
      'align',
      'justify',
      'text',
      'format',
      'paragraph',
      'justifier',
      'justificar',
      'πλήρης στοίχιση',
      'wyjustuj',
      'justowanie',
    ],
  },
  {
    slug: 'align-left',
    component: AlignLeftIconComponent,
    categories: ['feather'],
    tags: [
      'align-left',
      'align',
      'left',
      'text',
      'format',
      'paragraph',
      'gauche',
      'izquierda',
      'αριστερά',
      'στοίχιση',
      'lewo',
      'wyrównaj',
    ],
  },
  {
    slug: 'align-right',
    component: AlignRightIconComponent,
    categories: ['feather'],
    tags: [
      'align-right',
      'align',
      'right',
      'text',
      'format',
      'paragraph',
      'droite',
      'derecha',
      'δεξιά',
      'στοίχιση',
      'prawo',
      'wyrównaj',
    ],
  },
  {
    slug: 'anchor',
    component: AnchorIconComponent,
    categories: ['feather'],
    tags: [
      'anchor',
      'ship',
      'boat',
      'marine',
      'ancre',
      'bateau',
      'ancla',
      'barco',
      'άγκυρα',
      'πλοίο',
      'kotwica',
      'statek',
    ],
  },
  {
    slug: 'aperture',
    component: ApertureIconComponent,
    categories: ['feather'],
    tags: [
      'aperture',
      'camera',
      'lens',
      'photo',
      'photography',
      'ouverture',
      'objectif',
      'apertura',
      'lente',
      'διάφραγμα',
      'φακός',
      'przysłona',
      'obiektyw',
    ],
  },
  {
    slug: 'archive',
    component: ArchiveIconComponent,
    categories: ['feather'],
    tags: [
      'archive',
      'storage',
      'box',
      'save',
      'backup',
      'archiver',
      'archivar',
      'almacenar',
      'αρχείο',
      'αρχειοθέτηση',
      'archiwum',
      'archiwizuj',
    ],
  },
  {
    slug: 'arrow-down',
    component: ArrowDownIconComponent,
    categories: ['feather'],
    tags: [
      'arrow-down',
      'arrow',
      'down',
      'south',
      'descend',
      'flèche',
      'bas',
      'flecha',
      'abajo',
      'βέλος',
      'κάτω',
      'strzałka',
      'dół',
    ],
  },
  {
    slug: 'arrow-down-left',
    component: ArrowDownLeftIconComponent,
    categories: ['feather'],
    tags: [
      'arrow-down-left',
      'arrow',
      'down',
      'left',
      'southwest',
      'flèche',
      'bas',
      'gauche',
      'flecha',
      'abajo',
      'izquierda',
      'βέλος',
      'κάτω',
      'αριστερά',
      'strzałka',
      'dół',
      'lewo',
    ],
  },
  {
    slug: 'arrow-down-right',
    component: ArrowDownRightIconComponent,
    categories: ['feather'],
    tags: [
      'arrow-down-right',
      'arrow',
      'down',
      'right',
      'southeast',
      'flèche',
      'bas',
      'droite',
      'flecha',
      'abajo',
      'derecha',
      'βέλος',
      'κάτω',
      'δεξιά',
      'strzałka',
      'dół',
      'prawo',
    ],
  },
  {
    slug: 'arrow-left',
    component: ArrowLeftIconComponent,
    categories: ['feather'],
    tags: [
      'arrow-left',
      'arrow',
      'left',
      'west',
      'back',
      'previous',
      'flèche',
      'gauche',
      'flecha',
      'izquierda',
      'βέλος',
      'αριστερά',
      'strzałka',
      'lewo',
    ],
  },
  {
    slug: 'arrow-right',
    component: ArrowRightIconComponent,
    categories: ['feather'],
    tags: [
      'arrow-right',
      'arrow',
      'right',
      'east',
      'forward',
      'next',
      'flèche',
      'droite',
      'flecha',
      'derecha',
      'βέλος',
      'δεξιά',
      'strzałka',
      'prawo',
    ],
  },
  {
    slug: 'arrow-up',
    component: ArrowUpIconComponent,
    categories: ['feather'],
    tags: [
      'arrow-up',
      'arrow',
      'up',
      'north',
      'ascend',
      'flèche',
      'haut',
      'flecha',
      'arriba',
      'βέλος',
      'πάνω',
      'strzałka',
      'góra',
    ],
  },
  {
    slug: 'arrow-up-left',
    component: ArrowUpLeftIconComponent,
    categories: ['feather'],
    tags: [
      'arrow-up-left',
      'arrow',
      'up',
      'left',
      'northwest',
      'flèche',
      'haut',
      'gauche',
      'flecha',
      'arriba',
      'izquierda',
      'βέλος',
      'πάνω',
      'αριστερά',
      'strzałka',
      'góra',
      'lewo',
    ],
  },
  {
    slug: 'arrow-up-right',
    component: ArrowUpRightIconComponent,
    categories: ['feather'],
    tags: [
      'arrow-up-right',
      'arrow',
      'up',
      'right',
      'northeast',
      'flèche',
      'haut',
      'droite',
      'flecha',
      'arriba',
      'derecha',
      'βέλος',
      'πάνω',
      'δεξιά',
      'strzałka',
      'góra',
      'prawo',
    ],
  },
  {
    slug: 'at-sign',
    component: AtSignIconComponent,
    categories: ['feather'],
    tags: [
      'at-sign',
      'at',
      'sign',
      'email',
      'mention',
      'arobase',
      'arroba',
      'παπάκι',
      'małpa',
    ],
  },
  {
    slug: 'award',
    component: AwardIconComponent,
    categories: ['feather'],
    tags: [
      'award',
      'medal',
      'prize',
      'trophy',
      'achievement',
      'badge',
      'récompense',
      'médaille',
      'premio',
      'medalla',
      'βραβείο',
      'μετάλλιο',
      'nagroda',
      'medal',
    ],
  },
  {
    slug: 'bar-chart',
    component: BarChartIconComponent,
    categories: ['feather'],
    tags: [
      'bar-chart',
      'bar',
      'chart',
      'graph',
      'statistics',
      'analytics',
      'graphique',
      'gráfico',
      'estadísticas',
      'γράφημα',
      'στατιστικά',
      'wykres',
      'statystyki',
    ],
  },
  {
    slug: 'battery',
    component: BatteryIconComponent,
    categories: ['feather'],
    tags: [
      'battery',
      'power',
      'energy',
      'charge',
      'batterie',
      'batería',
      'energía',
      'μπαταρία',
      'ενέργεια',
      'bateria',
      'energia',
    ],
  },
  {
    slug: 'battery-charging',
    component: BatteryChargingIconComponent,
    categories: ['feather'],
    tags: [
      'battery-charging',
      'battery',
      'charging',
      'power',
      'energy',
      'charge',
      'batterie',
      'charge',
      'batería',
      'cargando',
      'μπαταρία',
      'φόρτιση',
      'bateria',
      'ładowanie',
    ],
  },
  {
    slug: 'bell',
    component: BellIconComponent,
    categories: ['feather'],
    tags: [
      'bell',
      'notification',
      'alert',
      'ring',
      'reminder',
      'cloche',
      'notification',
      'campana',
      'notificación',
      'καμπάνα',
      'ειδοποίηση',
      'dzwonek',
      'powiadomienie',
    ],
  },
  {
    slug: 'bell-off',
    component: BellOffIconComponent,
    categories: ['feather'],
    tags: [
      'bell-off',
      'bell',
      'off',
      'mute',
      'silent',
      'notification',
      'silence',
      'silencio',
      'mudo',
      'σίγαση',
      'wyciszony',
      'cisza',
    ],
  },
  {
    slug: 'bluetooth',
    component: BluetoothIconComponent,
    categories: ['feather'],
    tags: [
      'bluetooth',
      'wireless',
      'connection',
      'connect',
      'sans-fil',
      'inalámbrico',
      'ασύρματο',
      'σύνδεση',
      'bezprzewodowy',
    ],
  },
  {
    slug: 'bold',
    component: BoldIconComponent,
    categories: ['feather'],
    tags: [
      'bold',
      'text',
      'format',
      'strong',
      'weight',
      'gras',
      'negrita',
      'έντονα',
      'pogrubienie',
    ],
  },
  {
    slug: 'book',
    component: BookIconComponent,
    categories: ['feather'],
    tags: [
      'book',
      'read',
      'library',
      'literature',
      'study',
      'livre',
      'lecture',
      'libro',
      'leer',
      'βιβλίο',
      'ανάγνωση',
      'książka',
      'czytać',
    ],
  },
  {
    slug: 'book-open',
    component: BookOpenIconComponent,
    categories: ['feather'],
    tags: [
      'book-open',
      'book',
      'open',
      'read',
      'literature',
      'study',
      'livre',
      'ouvert',
      'libro',
      'abierto',
      'βιβλίο',
      'ανοιχτό',
      'książka',
      'otwarta',
    ],
  },
  {
    slug: 'bookmark',
    component: BookmarkIconComponent,
    categories: ['feather'],
    tags: [
      'bookmark',
      'save',
      'favorite',
      'mark',
      'tag',
      'marque-page',
      'favori',
      'marcador',
      'favorito',
      'σελιδοδείκτης',
      'αγαπημένο',
      'zakładka',
      'ulubione',
    ],
  },
  {
    slug: 'bottle',
    component: BottleIconComponent,
    categories: ['eagami'],
    tags: [
      'bottle',
      'drink',
      'water',
      'beverage',
      'container',
      'bouteille',
      'botella',
      'agua',
      'μπουκάλι',
      'νερό',
      'butelka',
      'woda',
    ],
  },
  {
    slug: 'box',
    component: BoxIconComponent,
    categories: ['feather'],
    tags: [
      'box',
      'package',
      'parcel',
      'cube',
      'container',
      'boîte',
      'colis',
      'caja',
      'paquete',
      'κουτί',
      'πακέτο',
      'pudełko',
      'paczka',
    ],
  },
  {
    slug: 'briefcase',
    component: BriefcaseIconComponent,
    categories: ['feather'],
    tags: [
      'briefcase',
      'work',
      'business',
      'job',
      'office',
      'mallette',
      'travail',
      'maletín',
      'trabajo',
      'χαρτοφύλακας',
      'εργασία',
      'teczka',
      'praca',
    ],
  },
  {
    slug: 'calendar',
    component: CalendarIconComponent,
    categories: ['feather'],
    tags: [
      'calendar',
      'date',
      'schedule',
      'event',
      'day',
      'month',
      'calendrier',
      'date',
      'calendario',
      'fecha',
      'ημερολόγιο',
      'ημερομηνία',
      'kalendarz',
      'data',
    ],
  },
  {
    slug: 'camera',
    component: CameraIconComponent,
    categories: ['feather'],
    tags: [
      'camera',
      'photo',
      'photography',
      'picture',
      'snapshot',
      'appareil photo',
      'cámara',
      'foto',
      'κάμερα',
      'φωτογραφία',
      'aparat',
      'zdjęcie',
    ],
  },
  {
    slug: 'candle',
    component: CandleIconComponent,
    categories: ['eagami'],
    tags: [
      'candle',
      'light',
      'flame',
      'wax',
      'bougie',
      'flamme',
      'vela',
      'llama',
      'κερί',
      'φλόγα',
      'świeca',
      'płomień',
    ],
  },
  {
    slug: 'check',
    component: CheckIconComponent,
    categories: ['feather'],
    tags: [
      'check',
      'tick',
      'confirm',
      'done',
      'ok',
      'yes',
      'coche',
      'valider',
      'marca',
      'confirmar',
      'τσεκ',
      'επιβεβαίωση',
      'zaznacz',
      'potwierdź',
    ],
  },
  {
    slug: 'check-circle',
    component: CheckCircleIconComponent,
    categories: ['feather'],
    tags: [
      'check-circle',
      'check',
      'circle',
      'tick',
      'confirm',
      'done',
      'success',
      'validé',
      'coche',
      'confirmar',
      'éxito',
      'επιτυχία',
      'επιβεβαίωση',
      'sukces',
      'potwierdzono',
    ],
  },
  {
    slug: 'chevron-down',
    component: ChevronDownIconComponent,
    categories: ['feather'],
    tags: [
      'chevron-down',
      'chevron',
      'down',
      'arrow',
      'expand',
      'dropdown',
      'bas',
      'abajo',
      'κάτω',
      'dół',
    ],
  },
  {
    slug: 'chevron-left',
    component: ChevronLeftIconComponent,
    categories: ['feather'],
    tags: [
      'chevron-left',
      'chevron',
      'left',
      'arrow',
      'back',
      'previous',
      'gauche',
      'izquierda',
      'αριστερά',
      'lewo',
    ],
  },
  {
    slug: 'chevron-right',
    component: ChevronRightIconComponent,
    categories: ['feather'],
    tags: [
      'chevron-right',
      'chevron',
      'right',
      'arrow',
      'forward',
      'next',
      'droite',
      'derecha',
      'δεξιά',
      'prawo',
    ],
  },
  {
    slug: 'chevron-up',
    component: ChevronUpIconComponent,
    categories: ['feather'],
    tags: [
      'chevron-up',
      'chevron',
      'up',
      'arrow',
      'collapse',
      'haut',
      'arriba',
      'πάνω',
      'góra',
    ],
  },
  {
    slug: 'chevrons-up-down',
    component: ChevronsUpDownIconComponent,
    categories: ['feather'],
    tags: [
      'chevrons-up-down',
      'chevrons',
      'up',
      'down',
      'sort',
      'expand',
      'haut',
      'bas',
      'arriba',
      'abajo',
      'πάνω',
      'κάτω',
      'góra',
      'dół',
    ],
  },
  {
    slug: 'chrome',
    component: ChromeIconComponent,
    categories: ['brand'],
    tags: [
      'chrome',
      'browser',
      'google',
      'web',
      'navigateur',
      'navegador',
      'περιηγητής',
      'przeglądarka',
    ],
  },
  {
    slug: 'circle',
    component: CircleIconComponent,
    categories: ['eagami'],
    tags: [
      'circle',
      'round',
      'oval',
      'disc',
      'shape',
      'cercle',
      'círculo',
      'κύκλος',
      'okrąg',
      'koło',
    ],
  },
  {
    slug: 'clipboard',
    component: ClipboardIconComponent,
    categories: ['feather'],
    tags: [
      'clipboard',
      'copy',
      'paste',
      'notes',
      'list',
      'presse-papiers',
      'portapapeles',
      'πρόχειρο',
      'schowek',
      'notatki',
    ],
  },
  {
    slug: 'clock',
    component: ClockIconComponent,
    categories: ['feather'],
    tags: [
      'clock',
      'time',
      'watch',
      'hour',
      'horloge',
      'temps',
      'reloj',
      'tiempo',
      'ρολόι',
      'ώρα',
      'zegar',
      'czas',
    ],
  },
  {
    slug: 'cloud',
    component: CloudIconComponent,
    categories: ['feather'],
    tags: [
      'cloud',
      'weather',
      'sky',
      'storage',
      'nuage',
      'météo',
      'nube',
      'tiempo',
      'σύννεφο',
      'καιρός',
      'chmura',
      'pogoda',
    ],
  },
  {
    slug: 'cloudflare',
    component: CloudflareIconComponent,
    categories: ['brand'],
    tags: ['cloudflare', 'cdn', 'cloud', 'hosting', 'dns'],
  },
  {
    slug: 'code',
    component: CodeIconComponent,
    categories: ['feather'],
    tags: [
      'code',
      'programming',
      'developer',
      'syntax',
      'brackets',
      'script',
      'programmation',
      'développement',
      'código',
      'programación',
      'κώδικας',
      'προγραμματισμός',
      'kod',
      'programowanie',
    ],
  },
  {
    slug: 'codepen',
    component: CodepenIconComponent,
    categories: ['brand'],
    tags: ['codepen', 'code', 'editor', 'sandbox', 'frontend'],
  },
  {
    slug: 'codesandbox',
    component: CodesandboxIconComponent,
    categories: ['brand'],
    tags: ['codesandbox', 'sandbox', 'code', 'editor', 'frontend'],
  },
  {
    slug: 'coffee',
    component: CoffeeIconComponent,
    categories: ['feather'],
    tags: [
      'coffee',
      'drink',
      'cup',
      'cafe',
      'mug',
      'café',
      'taza',
      'καφές',
      'κούπα',
      'kawa',
      'kubek',
    ],
  },
  {
    slug: 'columns',
    component: ColumnsIconComponent,
    categories: ['feather'],
    tags: [
      'columns',
      'layout',
      'split',
      'grid',
      'panel',
      'colonnes',
      'columnas',
      'στήλες',
      'διάταξη',
      'kolumny',
      'układ',
    ],
  },
  {
    slug: 'command',
    component: CommandIconComponent,
    categories: ['feather'],
    tags: [
      'command',
      'keyboard',
      'shortcut',
      'cmd',
      'mac',
      'commande',
      'comando',
      'εντολή',
      'πληκτρολόγιο',
      'komenda',
      'klawisz',
    ],
  },
  {
    slug: 'compass',
    component: CompassIconComponent,
    categories: ['feather'],
    tags: [
      'compass',
      'navigation',
      'direction',
      'map',
      'north',
      'boussole',
      'brújula',
      'navegación',
      'πυξίδα',
      'πλοήγηση',
      'kompas',
      'nawigacja',
    ],
  },
  {
    slug: 'copy',
    component: CopyIconComponent,
    categories: ['feather'],
    tags: [
      'copy',
      'duplicate',
      'clone',
      'paste',
      'clipboard',
      'copier',
      'copiar',
      'duplicar',
      'αντιγραφή',
      'kopiuj',
      'duplikuj',
    ],
  },
  {
    slug: 'corner-down-left',
    component: CornerDownLeftIconComponent,
    categories: ['feather'],
    tags: [
      'corner-down-left',
      'corner',
      'down',
      'left',
      'arrow',
      'return',
      'enter',
      'coin',
      'bas',
      'gauche',
      'esquina',
      'abajo',
      'izquierda',
      'γωνία',
      'κάτω',
      'αριστερά',
      'róg',
      'dół',
      'lewo',
    ],
  },
  {
    slug: 'corner-down-right',
    component: CornerDownRightIconComponent,
    categories: ['feather'],
    tags: [
      'corner-down-right',
      'corner',
      'down',
      'right',
      'arrow',
      'coin',
      'bas',
      'droite',
      'esquina',
      'abajo',
      'derecha',
      'γωνία',
      'κάτω',
      'δεξιά',
      'róg',
      'dół',
      'prawo',
    ],
  },
  {
    slug: 'corner-up-left',
    component: CornerUpLeftIconComponent,
    categories: ['feather'],
    tags: [
      'corner-up-left',
      'corner',
      'up',
      'left',
      'arrow',
      'undo',
      'coin',
      'haut',
      'gauche',
      'esquina',
      'arriba',
      'izquierda',
      'γωνία',
      'πάνω',
      'αριστερά',
      'róg',
      'góra',
      'lewo',
    ],
  },
  {
    slug: 'corner-up-right',
    component: CornerUpRightIconComponent,
    categories: ['feather'],
    tags: [
      'corner-up-right',
      'corner',
      'up',
      'right',
      'arrow',
      'redo',
      'coin',
      'haut',
      'droite',
      'esquina',
      'arriba',
      'derecha',
      'γωνία',
      'πάνω',
      'δεξιά',
      'róg',
      'góra',
      'prawo',
    ],
  },
  {
    slug: 'cpu',
    component: CpuIconComponent,
    categories: ['feather'],
    tags: [
      'cpu',
      'processor',
      'chip',
      'computer',
      'hardware',
      'processeur',
      'puce',
      'procesador',
      'chip',
      'επεξεργαστής',
      'τσιπ',
      'procesor',
      'układ',
    ],
  },
  {
    slug: 'credit-card',
    component: CreditCardIconComponent,
    categories: ['feather'],
    tags: [
      'credit-card',
      'credit',
      'card',
      'payment',
      'money',
      'bank',
      'carte',
      'paiement',
      'tarjeta',
      'pago',
      'κάρτα',
      'πληρωμή',
      'karta',
      'płatność',
    ],
  },
  {
    slug: 'crop',
    component: CropIconComponent,
    categories: ['feather'],
    tags: [
      'crop',
      'image',
      'cut',
      'trim',
      'edit',
      'recadrer',
      'rogner',
      'recortar',
      'περικοπή',
      'κόψιμο',
      'kadruj',
      'przytnij',
    ],
  },
  {
    slug: 'crosshair',
    component: CrosshairIconComponent,
    categories: ['feather'],
    tags: [
      'crosshair',
      'target',
      'aim',
      'focus',
      'precision',
      'cible',
      'mira',
      'objetivo',
      'στόχος',
      'σταυρόνημα',
      'celownik',
      'cel',
    ],
  },
  {
    slug: 'database',
    component: DatabaseIconComponent,
    categories: ['feather'],
    tags: [
      'database',
      'storage',
      'data',
      'server',
      'sql',
      'base de données',
      'données',
      'base de datos',
      'datos',
      'βάση δεδομένων',
      'δεδομένα',
      'baza danych',
      'dane',
    ],
  },
  {
    slug: 'delete',
    component: DeleteIconComponent,
    categories: ['feather'],
    tags: [
      'delete',
      'remove',
      'erase',
      'backspace',
      'clear',
      'supprimer',
      'effacer',
      'eliminar',
      'borrar',
      'διαγραφή',
      'usuń',
      'kasuj',
    ],
  },
  {
    slug: 'disc',
    component: DiscIconComponent,
    categories: ['feather'],
    tags: [
      'disc',
      'cd',
      'dvd',
      'record',
      'music',
      'album',
      'disque',
      'disco',
      'δίσκος',
      'μουσική',
      'płyta',
      'dysk',
    ],
  },
  {
    slug: 'discord',
    component: DiscordIconComponent,
    categories: ['brand'],
    tags: ['discord', 'chat', 'messaging', 'gaming', 'community'],
  },
  {
    slug: 'divide',
    component: DivideIconComponent,
    categories: ['feather'],
    tags: [
      'divide',
      'division',
      'math',
      'split',
      'diviser',
      'mathématiques',
      'dividir',
      'matemáticas',
      'διαίρεση',
      'μαθηματικά',
      'dzielenie',
      'matematyka',
    ],
  },
  {
    slug: 'docker',
    component: DockerIconComponent,
    categories: ['brand'],
    tags: ['docker', 'container', 'devops', 'image', 'virtualization'],
  },
  {
    slug: 'dollar-sign',
    component: DollarSignIconComponent,
    categories: ['feather'],
    tags: [
      'dollar-sign',
      'dollar',
      'sign',
      'money',
      'currency',
      'usd',
      'price',
      'argent',
      'devise',
      'dinero',
      'moneda',
      'δολάριο',
      'χρήμα',
      'dolar',
      'pieniądze',
    ],
  },
  {
    slug: 'download',
    component: DownloadIconComponent,
    categories: ['feather'],
    tags: [
      'download',
      'save',
      'arrow',
      'get',
      'install',
      'télécharger',
      'descargar',
      'bajar',
      'λήψη',
      'κατέβασμα',
      'pobierz',
      'ściągnij',
    ],
  },
  {
    slug: 'download-cloud',
    component: DownloadCloudIconComponent,
    categories: ['feather'],
    tags: [
      'download-cloud',
      'download',
      'cloud',
      'save',
      'sync',
      'télécharger',
      'nuage',
      'descargar',
      'nube',
      'λήψη',
      'σύννεφο',
      'pobierz',
      'chmura',
    ],
  },
  {
    slug: 'dropbox',
    component: DropboxIconComponent,
    categories: ['brand'],
    tags: ['dropbox', 'storage', 'cloud', 'files', 'sync'],
  },
  {
    slug: 'droplet',
    component: DropletIconComponent,
    categories: ['feather'],
    tags: [
      'droplet',
      'water',
      'drop',
      'liquid',
      'rain',
      'goutte',
      'eau',
      'gota',
      'agua',
      'σταγόνα',
      'νερό',
      'kropla',
      'woda',
    ],
  },
  {
    slug: 'eagami',
    component: EagamiIconComponent,
    categories: ['eagami', 'brand'],
    tags: ['logo', 'mark'],
  },
  {
    slug: 'edit',
    component: EditIconComponent,
    categories: ['feather'],
    tags: [
      'edit',
      'pencil',
      'modify',
      'change',
      'write',
      'éditer',
      'modifier',
      'editar',
      'modificar',
      'επεξεργασία',
      'τροποποίηση',
      'edytuj',
      'zmień',
    ],
  },
  {
    slug: 'edit-2',
    component: Edit2IconComponent,
    categories: ['feather'],
    tags: [
      'edit-2',
      'edit',
      '2',
      'pencil',
      'modify',
      'write',
      'éditer',
      'crayon',
      'editar',
      'lápiz',
      'επεξεργασία',
      'μολύβι',
      'edytuj',
      'ołówek',
    ],
  },
  {
    slug: 'edit-3',
    component: Edit3IconComponent,
    categories: ['feather'],
    tags: [
      'edit-3',
      'edit',
      '3',
      'pencil',
      'modify',
      'write',
      'éditer',
      'crayon',
      'editar',
      'lápiz',
      'επεξεργασία',
      'μολύβι',
      'edytuj',
      'ołówek',
    ],
  },
  {
    slug: 'external-link',
    component: ExternalLinkIconComponent,
    categories: ['feather'],
    tags: [
      'external-link',
      'external',
      'link',
      'open',
      'new',
      'tab',
      'lien',
      'externe',
      'enlace',
      'externo',
      'εξωτερικός',
      'σύνδεσμος',
      'zewnętrzny',
      'link',
    ],
  },
  {
    slug: 'eye',
    component: EyeIconComponent,
    categories: ['feather'],
    tags: [
      'eye',
      'view',
      'see',
      'visible',
      'show',
      'watch',
      'œil',
      'voir',
      'ojo',
      'ver',
      'μάτι',
      'δες',
      'oko',
      'pokaż',
    ],
  },
  {
    slug: 'eye-off',
    component: EyeOffIconComponent,
    categories: ['feather'],
    tags: [
      'eye-off',
      'eye',
      'off',
      'hide',
      'hidden',
      'invisible',
      'caché',
      'masquer',
      'oculto',
      'esconder',
      'κρυφό',
      'απόκρυψη',
      'ukryj',
      'niewidoczne',
    ],
  },
  {
    slug: 'facebook',
    component: FacebookIconComponent,
    categories: ['brand'],
    tags: ['facebook', 'social', 'meta', 'network'],
  },
  {
    slug: 'fast-forward',
    component: FastForwardIconComponent,
    categories: ['feather'],
    tags: [
      'fast-forward',
      'fast',
      'forward',
      'play',
      'skip',
      'speed',
      'avance rapide',
      'rápido',
      'γρήγορη μετάβαση',
      'μπροστά',
      'przewiń',
      'do przodu',
      'music',
      'audio',
    ],
  },
  {
    slug: 'feather',
    component: FeatherIconComponent,
    categories: ['feather'],
    tags: [
      'light',
      'write',
      'quill',
      'plume',
      'pluma',
      'φτερό',
      'πένα',
      'pióro',
      'lekki',
    ],
  },
  {
    slug: 'figma',
    component: FigmaIconComponent,
    categories: ['brand'],
    tags: ['figma', 'design', 'ui', 'tool'],
  },
  {
    slug: 'file',
    component: FileIconComponent,
    categories: ['feather'],
    tags: [
      'file',
      'document',
      'paper',
      'page',
      'fichier',
      'document',
      'archivo',
      'documento',
      'αρχείο',
      'έγγραφο',
      'plik',
      'dokument',
    ],
  },
  {
    slug: 'file-minus',
    component: FileMinusIconComponent,
    categories: ['feather'],
    tags: [
      'file-minus',
      'file',
      'minus',
      'remove',
      'delete',
      'document',
      'fichier',
      'archivo',
      'eliminar',
      'αρχείο',
      'αφαίρεση',
      'plik',
      'usuń',
    ],
  },
  {
    slug: 'file-plus',
    component: FilePlusIconComponent,
    categories: ['feather'],
    tags: [
      'file-plus',
      'file',
      'plus',
      'add',
      'new',
      'create',
      'document',
      'fichier',
      'nouveau',
      'archivo',
      'nuevo',
      'αρχείο',
      'νέο',
      'plik',
      'nowy',
    ],
  },
  {
    slug: 'file-text',
    component: FileTextIconComponent,
    categories: ['feather'],
    tags: [
      'file-text',
      'file',
      'text',
      'document',
      'page',
      'fichier',
      'texte',
      'archivo',
      'texto',
      'αρχείο',
      'κείμενο',
      'plik',
      'tekst',
    ],
  },
  {
    slug: 'film',
    component: FilmIconComponent,
    categories: ['feather'],
    tags: [
      'film',
      'movie',
      'video',
      'cinema',
      'reel',
      'película',
      'cine',
      'ταινία',
      'σινεμά',
      'kino',
    ],
  },
  {
    slug: 'filter',
    component: FilterIconComponent,
    categories: ['feather'],
    tags: [
      'filter',
      'funnel',
      'sort',
      'refine',
      'filtre',
      'entonnoir',
      'filtro',
      'embudo',
      'φίλτρο',
      'χωνί',
      'filtr',
      'lejek',
    ],
  },
  {
    slug: 'flag',
    component: FlagIconComponent,
    categories: ['feather'],
    tags: [
      'flag',
      'mark',
      'report',
      'country',
      'banner',
      'drapeau',
      'bandera',
      'σημαία',
      'flaga',
      'oznacz',
    ],
  },
  {
    slug: 'folder',
    component: FolderIconComponent,
    categories: ['feather'],
    tags: [
      'folder',
      'directory',
      'files',
      'storage',
      'dossier',
      'répertoire',
      'carpeta',
      'directorio',
      'φάκελος',
      'κατάλογος',
      'folder',
      'katalog',
    ],
  },
  {
    slug: 'frown',
    component: FrownIconComponent,
    categories: ['feather'],
    tags: [
      'frown',
      'sad',
      'unhappy',
      'emoji',
      'face',
      'triste',
      'mécontent',
      'enfadado',
      'cara',
      'λυπημένος',
      'πρόσωπο',
      'smutny',
      'twarz',
    ],
  },
  {
    slug: 'gift',
    component: GiftIconComponent,
    categories: ['feather'],
    tags: [
      'gift',
      'present',
      'birthday',
      'box',
      'reward',
      'cadeau',
      'regalo',
      'sorpresa',
      'δώρο',
      'έκπληξη',
      'prezent',
      'podarunek',
    ],
  },
  {
    slug: 'git-branch',
    component: GitBranchIconComponent,
    categories: ['feather'],
    tags: [
      'git-branch',
      'git',
      'branch',
      'version',
      'control',
      'fork',
      'branche',
      'rama',
      'κλάδος',
      'gałąź',
    ],
  },
  {
    slug: 'git-commit',
    component: GitCommitIconComponent,
    categories: ['feather'],
    tags: [
      'git-commit',
      'git',
      'commit',
      'version',
      'control',
      'change',
      'commit',
      'cambio',
      'υποβολή',
      'commit',
    ],
  },
  {
    slug: 'git-merge',
    component: GitMergeIconComponent,
    categories: ['feather'],
    tags: [
      'git-merge',
      'git',
      'merge',
      'version',
      'control',
      'combine',
      'fusion',
      'fusionner',
      'fusión',
      'συγχώνευση',
      'scalanie',
      'merge',
    ],
  },
  {
    slug: 'git-pull-request',
    component: GitPullRequestIconComponent,
    categories: ['feather'],
    tags: [
      'git-pull-request',
      'git',
      'pull',
      'request',
      'pr',
      'version',
      'control',
      'review',
      'demande',
      'solicitud',
      'αίτημα',
      'prośba',
    ],
  },
  {
    slug: 'github',
    component: GithubIconComponent,
    categories: ['brand'],
    tags: ['github', 'git', 'repository', 'repo', 'source code', 'version control'],
  },
  {
    slug: 'gitlab',
    component: GitlabIconComponent,
    categories: ['brand'],
    tags: ['gitlab', 'git', 'repository', 'repo', 'source code', 'version control'],
  },
  {
    slug: 'globe',
    component: GlobeIconComponent,
    categories: ['feather'],
    tags: [
      'globe',
      'world',
      'earth',
      'international',
      'language',
      'web',
      'monde',
      'terre',
      'mundo',
      'tierra',
      'κόσμος',
      'γη',
      'świat',
      'ziemia',
    ],
  },
  {
    slug: 'google',
    component: GoogleIconComponent,
    categories: ['brand'],
    tags: ['google', 'search', 'web'],
  },
  {
    slug: 'grid',
    component: GridIconComponent,
    categories: ['feather'],
    tags: [
      'grid',
      'layout',
      'tiles',
      'gallery',
      'cells',
      'grille',
      'cuadrícula',
      'πλέγμα',
      'siatka',
      'układ',
    ],
  },
  {
    slug: 'hard-drive',
    component: HardDriveIconComponent,
    categories: ['feather'],
    tags: [
      'hard-drive',
      'hard',
      'drive',
      'storage',
      'disk',
      'memory',
      'disque dur',
      'almacenamiento',
      'disco duro',
      'σκληρός δίσκος',
      'αποθήκευση',
      'dysk twardy',
      'pamięć',
    ],
  },
  {
    slug: 'hash',
    component: HashIconComponent,
    categories: ['feather'],
    tags: [
      'hash',
      'hashtag',
      'pound',
      'number',
      'tag',
      'dièse',
      'numeral',
      'almohadilla',
      'δίεση',
      'κατακερματισμός',
      'krzyżyk',
      'hasztag',
    ],
  },
  {
    slug: 'headphones',
    component: HeadphonesIconComponent,
    categories: ['feather'],
    tags: [
      'headphones',
      'audio',
      'music',
      'listen',
      'sound',
      'casque',
      'écouteurs',
      'auriculares',
      'ακουστικά',
      'μουσική',
      'słuchawki',
      'audio',
    ],
  },
  {
    slug: 'heart',
    component: HeartIconComponent,
    categories: ['feather'],
    tags: [
      'heart',
      'love',
      'like',
      'favorite',
      'romance',
      'cœur',
      'amour',
      'corazón',
      'amor',
      'καρδιά',
      'αγάπη',
      'serce',
      'miłość',
    ],
  },
  {
    slug: 'help-circle',
    component: HelpCircleIconComponent,
    categories: ['feather'],
    tags: [
      'help-circle',
      'help',
      'circle',
      'question',
      'support',
      'info',
      'aide',
      'question',
      'ayuda',
      'pregunta',
      'βοήθεια',
      'ερώτηση',
      'pomoc',
      'pytanie',
    ],
  },
  {
    slug: 'heptagon',
    component: HeptagonIconComponent,
    categories: ['eagami'],
    tags: [
      'heptagon',
      'seven-sided',
      'polygon',
      'shape',
      'heptagone',
      'heptágono',
      'επτάγωνο',
      'siedmiokąt',
    ],
  },
  {
    slug: 'hexagon',
    component: HexagonIconComponent,
    categories: ['eagami'],
    tags: [
      'hexagon',
      'six-sided',
      'polygon',
      'shape',
      'hexagone',
      'hexágono',
      'εξάγωνο',
      'sześciokąt',
    ],
  },
  {
    slug: 'home',
    component: HomeIconComponent,
    categories: ['feather'],
    tags: [
      'home',
      'house',
      'main',
      'start',
      'dashboard',
      'accueil',
      'maison',
      'inicio',
      'casa',
      'αρχική',
      'σπίτι',
      'dom',
      'początek',
    ],
  },
  {
    slug: 'image',
    component: ImageIconComponent,
    categories: ['feather'],
    tags: [
      'image',
      'picture',
      'photo',
      'gallery',
      'visual',
      'photo',
      'imagen',
      'foto',
      'εικόνα',
      'φωτογραφία',
      'obraz',
      'zdjęcie',
    ],
  },
  {
    slug: 'inbox',
    component: InboxIconComponent,
    categories: ['feather'],
    tags: [
      'inbox',
      'mail',
      'messages',
      'tray',
      'email',
      'boîte de réception',
      'bandeja',
      'entrada',
      'εισερχόμενα',
      'skrzynka',
      'odbiorcze',
    ],
  },
  {
    slug: 'info',
    component: InfoIconComponent,
    categories: ['feather'],
    tags: [
      'info',
      'information',
      'help',
      'about',
      'details',
      'information',
      'información',
      'πληροφορίες',
      'informacje',
    ],
  },
  {
    slug: 'italic',
    component: ItalicIconComponent,
    categories: ['feather'],
    tags: [
      'italic',
      'text',
      'format',
      'slant',
      'style',
      'italique',
      'cursiva',
      'πλάγια',
      'kursywa',
    ],
  },
  {
    slug: 'key',
    component: KeyIconComponent,
    categories: ['feather'],
    tags: [
      'key',
      'lock',
      'password',
      'security',
      'access',
      'clé',
      'mot de passe',
      'llave',
      'clave',
      'κλειδί',
      'κωδικός',
      'klucz',
      'hasło',
    ],
  },
  {
    slug: 'kubernetes',
    component: KubernetesIconComponent,
    categories: ['brand'],
    tags: ['kubernetes', 'k8s', 'container', 'devops', 'orchestration'],
  },
  {
    slug: 'lamp',
    component: LampIconComponent,
    categories: ['eagami'],
    tags: [
      'lamp',
      'light',
      'bulb',
      'lighting',
      'lampe',
      'lumière',
      'lámpara',
      'luz',
      'λάμπα',
      'φως',
      'lampa',
      'światło',
    ],
  },
  {
    slug: 'layers',
    component: LayersIconComponent,
    categories: ['feather'],
    tags: [
      'layers',
      'stack',
      'levels',
      'design',
      'overlay',
      'calques',
      'capas',
      'στρώματα',
      'επίπεδα',
      'warstwy',
      'stos',
    ],
  },
  {
    slug: 'layout',
    component: LayoutIconComponent,
    categories: ['feather'],
    tags: [
      'layout',
      'grid',
      'design',
      'structure',
      'template',
      'mise en page',
      'diseño',
      'plantilla',
      'διάταξη',
      'σχέδιο',
      'układ',
      'szablon',
    ],
  },
  {
    slug: 'life-buoy',
    component: LifeBuoyIconComponent,
    categories: ['feather'],
    tags: [
      'life-buoy',
      'life',
      'buoy',
      'help',
      'support',
      'rescue',
      'bouée',
      'sauvetage',
      'salvavidas',
      'ayuda',
      'σωσίβιο',
      'βοήθεια',
      'koło ratunkowe',
      'pomoc',
    ],
  },
  {
    slug: 'link',
    component: LinkIconComponent,
    categories: ['feather'],
    tags: [
      'link',
      'chain',
      'url',
      'connect',
      'hyperlink',
      'lien',
      'chaîne',
      'enlace',
      'cadena',
      'σύνδεσμος',
      'αλυσίδα',
      'link',
      'połączenie',
    ],
  },
  {
    slug: 'link-2',
    component: Link2IconComponent,
    categories: ['feather'],
    tags: [
      'link-2',
      'link',
      '2',
      'chain',
      'url',
      'connect',
      'hyperlink',
      'lien',
      'enlace',
      'σύνδεσμος',
      'link',
      'połączenie',
    ],
  },
  {
    slug: 'linkedin',
    component: LinkedinIconComponent,
    categories: ['brand'],
    tags: ['linkedin', 'social', 'network', 'professional', 'job'],
  },
  {
    slug: 'list',
    component: ListIconComponent,
    categories: ['feather'],
    tags: [
      'list',
      'menu',
      'items',
      'bullets',
      'todo',
      'liste',
      'lista',
      'menú',
      'λίστα',
      'κατάλογος',
      'lista',
      'spis',
    ],
  },
  {
    slug: 'loader',
    component: LoaderIconComponent,
    categories: ['feather'],
    tags: [
      'loader',
      'loading',
      'spinner',
      'wait',
      'progress',
      'chargement',
      'cargando',
      'cargador',
      'φόρτωση',
      'αναμονή',
      'ładowanie',
      'wczytywanie',
    ],
  },
  {
    slug: 'lock',
    component: LockIconComponent,
    categories: ['feather'],
    tags: [
      'lock',
      'secure',
      'password',
      'private',
      'closed',
      'verrou',
      'cadenas',
      'candado',
      'cerrado',
      'κλειδαριά',
      'ασφαλές',
      'kłódka',
      'zamknij',
    ],
  },
  {
    slug: 'log-in',
    component: LogInIconComponent,
    categories: ['feather'],
    tags: [
      'log-in',
      'log',
      'in',
      'login',
      'sign in',
      'enter',
      'access',
      'connexion',
      'iniciar sesión',
      'entrar',
      'σύνδεση',
      'είσοδος',
      'logowanie',
      'zaloguj',
    ],
  },
  {
    slug: 'log-out',
    component: LogOutIconComponent,
    categories: ['feather'],
    tags: [
      'log-out',
      'log',
      'out',
      'logout',
      'sign out',
      'exit',
      'leave',
      'déconnexion',
      'cerrar sesión',
      'salir',
      'αποσύνδεση',
      'έξοδος',
      'wylogowanie',
      'wyjdź',
    ],
  },
  {
    slug: 'mail',
    component: MailIconComponent,
    categories: ['feather'],
    tags: [
      'mail',
      'email',
      'message',
      'envelope',
      'letter',
      'courrier',
      'enveloppe',
      'correo',
      'mensaje',
      'αλληλογραφία',
      'φάκελος',
      'poczta',
      'wiadomość',
    ],
  },
  {
    slug: 'map',
    component: MapIconComponent,
    categories: ['feather'],
    tags: [
      'map',
      'location',
      'navigation',
      'directions',
      'geography',
      'carte',
      'mapa',
      'ubicación',
      'χάρτης',
      'τοποθεσία',
      'mapa',
      'lokalizacja',
    ],
  },
  {
    slug: 'map-pin',
    component: MapPinIconComponent,
    categories: ['feather'],
    tags: [
      'map-pin',
      'map',
      'pin',
      'location',
      'marker',
      'place',
      'épingle',
      'marqueur',
      'ubicación',
      'marcador',
      'καρφίτσα',
      'τοποθεσία',
      'pinezka',
      'lokalizacja',
    ],
  },
  {
    slug: 'mastercard',
    component: MastercardIconComponent,
    categories: ['brand'],
    tags: ['mastercard', 'card', 'payment', 'credit'],
  },
  {
    slug: 'maximize',
    component: MaximizeIconComponent,
    categories: ['feather'],
    tags: [
      'maximize',
      'expand',
      'fullscreen',
      'enlarge',
      'agrandir',
      'plein écran',
      'maximizar',
      'pantalla completa',
      'μεγιστοποίηση',
      'πλήρης οθόνη',
      'maksymalizuj',
      'pełny ekran',
    ],
  },
  {
    slug: 'maximize-2',
    component: Maximize2IconComponent,
    categories: ['feather'],
    tags: [
      'maximize-2',
      'maximize',
      '2',
      'expand',
      'fullscreen',
      'enlarge',
      'agrandir',
      'maximizar',
      'μεγιστοποίηση',
      'maksymalizuj',
    ],
  },
  {
    slug: 'meh',
    component: MehIconComponent,
    categories: ['feather'],
    tags: [
      'meh',
      'neutral',
      'face',
      'emoji',
      'indifferent',
      'neutre',
      'visage',
      'neutral',
      'cara',
      'ουδέτερος',
      'πρόσωπο',
      'obojętny',
      'twarz',
    ],
  },
  {
    slug: 'menu',
    component: MenuIconComponent,
    categories: ['feather'],
    tags: [
      'menu',
      'hamburger',
      'list',
      'navigation',
      'bars',
      'menú',
      'lista',
      'μενού',
      'navigacja',
      'lista',
    ],
  },
  {
    slug: 'message-circle',
    component: MessageCircleIconComponent,
    categories: ['feather'],
    tags: [
      'message-circle',
      'message',
      'circle',
      'chat',
      'comment',
      'bubble',
      'talk',
      'messagerie',
      'mensaje',
      'comentario',
      'μήνυμα',
      'συνομιλία',
      'wiadomość',
      'czat',
    ],
  },
  {
    slug: 'message-square',
    component: MessageSquareIconComponent,
    categories: ['feather'],
    tags: [
      'message-square',
      'message',
      'square',
      'chat',
      'comment',
      'bubble',
      'talk',
      'messagerie',
      'mensaje',
      'comentario',
      'μήνυμα',
      'συνομιλία',
      'wiadomość',
      'czat',
    ],
  },
  {
    slug: 'mic',
    component: MicIconComponent,
    categories: ['feather'],
    tags: [
      'mic',
      'microphone',
      'audio',
      'record',
      'voice',
      'sound',
      'micro',
      'micrófono',
      'voz',
      'μικρόφωνο',
      'φωνή',
      'mikrofon',
      'głos',
      'music',
    ],
  },
  {
    slug: 'mic-off',
    component: MicOffIconComponent,
    categories: ['feather'],
    tags: [
      'mic-off',
      'mic',
      'off',
      'mute',
      'microphone',
      'silent',
      'muet',
      'silencio',
      'mudo',
      'σίγαση',
      'wyciszony',
      'mikrofon',
      'music',
      'audio',
    ],
  },
  {
    slug: 'microsoft',
    component: MicrosoftIconComponent,
    categories: ['brand'],
    tags: ['microsoft', 'windows', 'company'],
  },
  {
    slug: 'minimize',
    component: MinimizeIconComponent,
    categories: ['feather'],
    tags: [
      'minimize',
      'shrink',
      'reduce',
      'collapse',
      'réduire',
      'minimizar',
      'reducir',
      'ελαχιστοποίηση',
      'σμίκρυνση',
      'minimalizuj',
      'zmniejsz',
    ],
  },
  {
    slug: 'minimize-2',
    component: Minimize2IconComponent,
    categories: ['feather'],
    tags: [
      'minimize-2',
      'minimize',
      '2',
      'shrink',
      'reduce',
      'collapse',
      'réduire',
      'minimizar',
      'ελαχιστοποίηση',
      'minimalizuj',
    ],
  },
  {
    slug: 'minus',
    component: MinusIconComponent,
    categories: ['feather'],
    tags: [
      'minus',
      'subtract',
      'remove',
      'less',
      'negative',
      'moins',
      'menos',
      'restar',
      'μείον',
      'αφαίρεση',
      'minus',
      'odejmij',
    ],
  },
  {
    slug: 'minus-circle',
    component: MinusCircleIconComponent,
    categories: ['feather'],
    tags: [
      'minus-circle',
      'minus',
      'circle',
      'remove',
      'subtract',
      'delete',
      'moins',
      'menos',
      'eliminar',
      'μείον',
      'αφαίρεση',
      'minus',
      'usuń',
    ],
  },
  {
    slug: 'minus-square',
    component: MinusSquareIconComponent,
    categories: ['feather'],
    tags: [
      'minus-square',
      'minus',
      'square',
      'remove',
      'subtract',
      'delete',
      'moins',
      'menos',
      'eliminar',
      'μείον',
      'αφαίρεση',
      'minus',
      'usuń',
    ],
  },
  {
    slug: 'mongodb',
    component: MongodbIconComponent,
    categories: ['brand'],
    tags: ['mongodb', 'database', 'nosql', 'mongo'],
  },
  {
    slug: 'monitor',
    component: MonitorIconComponent,
    categories: ['feather'],
    tags: [
      'monitor',
      'screen',
      'display',
      'computer',
      'desktop',
      'écran',
      'pantalla',
      'οθόνη',
      'monitor',
      'ekran',
    ],
  },
  {
    slug: 'moon',
    component: MoonIconComponent,
    categories: ['feather'],
    tags: [
      'moon',
      'night',
      'dark',
      'theme',
      'sleep',
      'lune',
      'nuit',
      'luna',
      'noche',
      'φεγγάρι',
      'νύχτα',
      'księżyc',
      'noc',
    ],
  },
  {
    slug: 'more-horizontal',
    component: MoreHorizontalIconComponent,
    categories: ['feather'],
    tags: [
      'more-horizontal',
      'more',
      'horizontal',
      'ellipsis',
      'menu',
      'dots',
      'options',
      'plus',
      'más',
      'περισσότερα',
      'więcej',
    ],
  },
  {
    slug: 'more-vertical',
    component: MoreVerticalIconComponent,
    categories: ['feather'],
    tags: [
      'more-vertical',
      'more',
      'vertical',
      'ellipsis',
      'menu',
      'dots',
      'options',
      'plus',
      'más',
      'περισσότερα',
      'więcej',
    ],
  },
  {
    slug: 'mouse-pointer',
    component: MousePointerIconComponent,
    categories: ['feather'],
    tags: [
      'mouse-pointer',
      'mouse',
      'pointer',
      'cursor',
      'click',
      'arrow',
      'souris',
      'curseur',
      'ratón',
      'cursor',
      'ποντίκι',
      'δείκτης',
      'mysz',
      'kursor',
    ],
  },
  {
    slug: 'move',
    component: MoveIconComponent,
    categories: ['feather'],
    tags: [
      'move',
      'drag',
      'arrows',
      'reposition',
      'shift',
      'déplacer',
      'mover',
      'μετακίνηση',
      'przenieś',
      'przesuń',
    ],
  },
  {
    slug: 'music',
    component: MusicIconComponent,
    categories: ['feather'],
    tags: [
      'music',
      'note',
      'audio',
      'song',
      'sound',
      'musique',
      'música',
      'canción',
      'μουσική',
      'τραγούδι',
      'muzyka',
      'piosenka',
    ],
  },
  {
    slug: 'navigation',
    component: NavigationIconComponent,
    categories: ['feather'],
    tags: [
      'navigation',
      'compass',
      'direction',
      'gps',
      'arrow',
      'navegación',
      'πλοήγηση',
      'nawigacja',
    ],
  },
  {
    slug: 'navigation-2',
    component: Navigation2IconComponent,
    categories: ['feather'],
    tags: [
      'navigation-2',
      'navigation',
      '2',
      'compass',
      'direction',
      'gps',
      'arrow',
      'navegación',
      'πλοήγηση',
      'nawigacja',
    ],
  },
  {
    slug: 'netlify',
    component: NetlifyIconComponent,
    categories: ['brand'],
    tags: ['netlify', 'hosting', 'deploy', 'jamstack'],
  },
  {
    slug: 'notion',
    component: NotionIconComponent,
    categories: ['brand'],
    tags: ['notion', 'notes', 'productivity', 'workspace'],
  },
  {
    slug: 'npm',
    component: NpmIconComponent,
    categories: ['brand'],
    tags: ['npm', 'node', 'package', 'registry', 'javascript'],
  },
  {
    slug: 'octagon',
    component: OctagonIconComponent,
    categories: ['feather'],
    tags: [
      'octagon',
      'shape',
      'stop',
      'sign',
      'eight',
      'octogone',
      'octágono',
      'οκτάγωνο',
      'σχήμα',
      'ośmiokąt',
      'kształt',
    ],
  },
  {
    slug: 'package',
    component: PackageIconComponent,
    categories: ['feather'],
    tags: [
      'package',
      'box',
      'parcel',
      'delivery',
      'shipping',
      'paquet',
      'colis',
      'paquete',
      'caja',
      'πακέτο',
      'κουτί',
      'paczka',
      'pudełko',
    ],
  },
  {
    slug: 'paperclip',
    component: PaperclipIconComponent,
    categories: ['feather'],
    tags: [
      'paperclip',
      'attach',
      'attachment',
      'clip',
      'file',
      'trombone',
      'pièce jointe',
      'clip',
      'adjunto',
      'συνδετήρας',
      'συνημμένο',
      'spinacz',
      'załącznik',
    ],
  },
  {
    slug: 'pause',
    component: PauseIconComponent,
    categories: ['feather'],
    tags: [
      'pause',
      'stop',
      'media',
      'player',
      'wait',
      'pausa',
      'παύση',
      'pauza',
      'wstrzymaj',
      'music',
      'audio',
    ],
  },
  {
    slug: 'pause-circle',
    component: PauseCircleIconComponent,
    categories: ['feather'],
    tags: [
      'pause-circle',
      'pause',
      'circle',
      'stop',
      'media',
      'player',
      'pausa',
      'παύση',
      'pauza',
      'wstrzymaj',
      'music',
      'audio',
    ],
  },
  {
    slug: 'paypal',
    component: PaypalIconComponent,
    categories: ['brand'],
    tags: ['paypal', 'payment', 'money', 'checkout'],
  },
  {
    slug: 'pencil',
    component: PencilIconComponent,
    categories: ['feather'],
    tags: [
      'pencil',
      'edit',
      'write',
      'draw',
      'modify',
      'crayon',
      'écrire',
      'lápiz',
      'escribir',
      'μολύβι',
      'γράψιμο',
      'ołówek',
      'pisać',
    ],
  },
  {
    slug: 'pentagon',
    component: PentagonIconComponent,
    categories: ['eagami'],
    tags: [
      'pentagon',
      'five-sided',
      'polygon',
      'shape',
      'pentagone',
      'pentágono',
      'πεντάγωνο',
      'pięciokąt',
    ],
  },
  {
    slug: 'percent',
    component: PercentIconComponent,
    categories: ['feather'],
    tags: [
      'percent',
      'percentage',
      'discount',
      'sale',
      'math',
      'pourcentage',
      'porcentaje',
      'descuento',
      'ποσοστό',
      'έκπτωση',
      'procent',
      'zniżka',
    ],
  },
  {
    slug: 'phone',
    component: PhoneIconComponent,
    categories: ['feather'],
    tags: [
      'phone',
      'call',
      'telephone',
      'contact',
      'mobile',
      'téléphone',
      'appel',
      'teléfono',
      'llamada',
      'τηλέφωνο',
      'κλήση',
      'telefon',
      'połączenie',
    ],
  },
  {
    slug: 'pie-chart',
    component: PieChartIconComponent,
    categories: ['feather'],
    tags: [
      'pie-chart',
      'pie',
      'chart',
      'graph',
      'statistics',
      'analytics',
      'circulaire',
      'gráfico',
      'circular',
      'γράφημα',
      'πίτα',
      'wykres',
      'kołowy',
    ],
  },
  {
    slug: 'play',
    component: PlayIconComponent,
    categories: ['feather'],
    tags: [
      'play',
      'start',
      'media',
      'player',
      'video',
      'lecture',
      'reproducir',
      'iniciar',
      'αναπαραγωγή',
      'παίξε',
      'odtwórz',
      'graj',
      'music',
      'audio',
    ],
  },
  {
    slug: 'play-circle',
    component: PlayCircleIconComponent,
    categories: ['feather'],
    tags: [
      'play-circle',
      'play',
      'circle',
      'start',
      'media',
      'video',
      'lecture',
      'reproducir',
      'αναπαραγωγή',
      'odtwórz',
      'music',
      'audio',
    ],
  },
  {
    slug: 'plus',
    component: PlusIconComponent,
    categories: ['feather'],
    tags: [
      'plus',
      'add',
      'new',
      'create',
      'positive',
      'ajouter',
      'añadir',
      'agregar',
      'συν',
      'προσθήκη',
      'dodaj',
      'plus',
    ],
  },
  {
    slug: 'plus-circle',
    component: PlusCircleIconComponent,
    categories: ['feather'],
    tags: [
      'plus-circle',
      'plus',
      'circle',
      'add',
      'new',
      'create',
      'ajouter',
      'añadir',
      'agregar',
      'συν',
      'προσθήκη',
      'dodaj',
    ],
  },
  {
    slug: 'plus-square',
    component: PlusSquareIconComponent,
    categories: ['feather'],
    tags: [
      'plus-square',
      'plus',
      'square',
      'add',
      'new',
      'create',
      'ajouter',
      'añadir',
      'agregar',
      'συν',
      'προσθήκη',
      'dodaj',
    ],
  },
  {
    slug: 'pocket',
    component: PocketIconComponent,
    categories: ['feather'],
    tags: [
      'pocket',
      'save',
      'read',
      'later',
      'bookmark',
      'poche',
      'bolsillo',
      'τσέπη',
      'kieszeń',
    ],
  },
  {
    slug: 'power',
    component: PowerIconComponent,
    categories: ['feather'],
    tags: [
      'power',
      'on',
      'off',
      'shutdown',
      'energy',
      'switch',
      'alimentation',
      'encender',
      'apagar',
      'τροφοδοσία',
      'ενέργεια',
      'zasilanie',
      'włącz',
    ],
  },
  {
    slug: 'printer',
    component: PrinterIconComponent,
    categories: ['feather'],
    tags: [
      'printer',
      'print',
      'document',
      'paper',
      'office',
      'imprimante',
      'imprimir',
      'impresora',
      'εκτυπωτής',
      'εκτύπωση',
      'drukarka',
      'drukuj',
    ],
  },
  {
    slug: 'radio',
    component: RadioIconComponent,
    categories: ['feather'],
    tags: [
      'radio',
      'broadcast',
      'wireless',
      'signal',
      'music',
      'señal',
      'ραδιόφωνο',
      'σήμα',
      'radio',
      'sygnał',
      'audio',
    ],
  },
  {
    slug: 'rectangle-horizontal',
    component: RectangleHorizontalIconComponent,
    categories: ['eagami'],
    tags: [
      'rectangle-horizontal',
      'rectangle',
      'horizontal',
      'landscape',
      'shape',
      'paysage',
      'horizontal',
      'apaisado',
      'οριζόντιο',
      'ορθογώνιο',
      'prostokąt',
      'poziomy',
    ],
  },
  {
    slug: 'rectangle-vertical',
    component: RectangleVerticalIconComponent,
    categories: ['eagami'],
    tags: [
      'rectangle-vertical',
      'rectangle',
      'vertical',
      'portrait',
      'shape',
      'portrait',
      'vertical',
      'κατακόρυφο',
      'ορθογώνιο',
      'prostokąt',
      'pionowy',
    ],
  },
  {
    slug: 'reddit',
    component: RedditIconComponent,
    categories: ['brand'],
    tags: ['reddit', 'social', 'forum', 'community'],
  },
  {
    slug: 'refresh-cw',
    component: RefreshCwIconComponent,
    categories: ['feather'],
    tags: [
      'refresh-cw',
      'refresh',
      'cw',
      'reload',
      'sync',
      'update',
      'rotate',
      'actualiser',
      'actualizar',
      'recargar',
      'ανανέωση',
      'odśwież',
      'załaduj',
    ],
  },
  {
    slug: 'repeat',
    component: RepeatIconComponent,
    categories: ['feather'],
    tags: [
      'repeat',
      'loop',
      'cycle',
      'replay',
      'again',
      'répéter',
      'repetir',
      'επανάληψη',
      'powtórz',
      'powtarzaj',
      'music',
      'audio',
    ],
  },
  {
    slug: 'rewind',
    component: RewindIconComponent,
    categories: ['feather'],
    tags: [
      'rewind',
      'back',
      'reverse',
      'media',
      'player',
      'retour',
      'rebobinar',
      'πίσω',
      'cofnij',
      'przewiń',
      'music',
      'audio',
    ],
  },
  {
    slug: 'rotate-ccw',
    component: RotateCcwIconComponent,
    categories: ['feather'],
    tags: [
      'rotate-ccw',
      'rotate',
      'ccw',
      'counterclockwise',
      'undo',
      'turn',
      'tourner',
      'girar',
      'περιστροφή',
      'obróć',
      'cofnij',
    ],
  },
  {
    slug: 'rotate-cw',
    component: RotateCwIconComponent,
    categories: ['feather'],
    tags: [
      'rotate-cw',
      'rotate',
      'cw',
      'clockwise',
      'redo',
      'turn',
      'tourner',
      'girar',
      'περιστροφή',
      'obróć',
      'ponów',
    ],
  },
  {
    slug: 'rss',
    component: RssIconComponent,
    categories: ['feather'],
    tags: [
      'rss',
      'feed',
      'subscribe',
      'news',
      'syndication',
      'flux',
      'noticias',
      'τροφοδοσία',
      'kanał',
      'subskrybuj',
    ],
  },
  {
    slug: 'save',
    component: SaveIconComponent,
    categories: ['feather'],
    tags: [
      'save',
      'disk',
      'store',
      'floppy',
      'download',
      'enregistrer',
      'guardar',
      'almacenar',
      'αποθήκευση',
      'zapisz',
      'dysk',
    ],
  },
  {
    slug: 'scissors',
    component: ScissorsIconComponent,
    categories: ['feather'],
    tags: [
      'scissors',
      'cut',
      'snip',
      'clip',
      'shears',
      'ciseaux',
      'couper',
      'tijeras',
      'cortar',
      'ψαλίδι',
      'κοπή',
      'nożyczki',
      'tnij',
    ],
  },
  {
    slug: 'search',
    component: SearchIconComponent,
    categories: ['feather'],
    tags: [
      'search',
      'find',
      'magnify',
      'lookup',
      'query',
      'recherche',
      'chercher',
      'buscar',
      'búsqueda',
      'αναζήτηση',
      'βρες',
      'szukaj',
      'wyszukaj',
    ],
  },
  {
    slug: 'send',
    component: SendIconComponent,
    categories: ['feather'],
    tags: [
      'send',
      'submit',
      'message',
      'plane',
      'mail',
      'envoyer',
      'enviar',
      'αποστολή',
      'στείλε',
      'wyślij',
      'nadaj',
    ],
  },
  {
    slug: 'server',
    component: ServerIconComponent,
    categories: ['feather'],
    tags: [
      'server',
      'database',
      'host',
      'hardware',
      'cloud',
      'serveur',
      'servidor',
      'διακομιστής',
      'εξυπηρετητής',
      'serwer',
      'host',
    ],
  },
  {
    slug: 'settings',
    component: SettingsIconComponent,
    categories: ['feather'],
    tags: [
      'settings',
      'gear',
      'cog',
      'preferences',
      'config',
      'options',
      'paramètres',
      'réglages',
      'ajustes',
      'configuración',
      'ρυθμίσεις',
      'παράμετροι',
      'ustawienia',
      'opcje',
    ],
  },
  {
    slug: 'share',
    component: ShareIconComponent,
    categories: ['feather'],
    tags: [
      'share',
      'send',
      'network',
      'social',
      'export',
      'partager',
      'compartir',
      'κοινοποίηση',
      'μοιραστείτε',
      'udostępnij',
      'wyślij',
    ],
  },
  {
    slug: 'share-2',
    component: Share2IconComponent,
    categories: ['feather'],
    tags: [
      'share-2',
      'share',
      '2',
      'send',
      'network',
      'social',
      'partager',
      'compartir',
      'κοινοποίηση',
      'udostępnij',
    ],
  },
  {
    slug: 'shield',
    component: ShieldIconComponent,
    categories: ['feather'],
    tags: [
      'shield',
      'security',
      'protect',
      'safe',
      'guard',
      'bouclier',
      'protection',
      'escudo',
      'seguridad',
      'ασπίδα',
      'προστασία',
      'tarcza',
      'ochrona',
    ],
  },
  {
    slug: 'shield-off',
    component: ShieldOffIconComponent,
    categories: ['feather'],
    tags: [
      'shield-off',
      'shield',
      'off',
      'unprotected',
      'unsafe',
      'disabled',
      'bouclier',
      'escudo',
      'ασπίδα',
      'tarcza',
    ],
  },
  {
    slug: 'shopping-bag',
    component: ShoppingBagIconComponent,
    categories: ['feather'],
    tags: [
      'shopping-bag',
      'shopping',
      'bag',
      'store',
      'purchase',
      'buy',
      'sac',
      'achats',
      'bolsa',
      'compras',
      'τσάντα',
      'αγορές',
      'torba',
      'zakupy',
    ],
  },
  {
    slug: 'shopping-cart',
    component: ShoppingCartIconComponent,
    categories: ['feather'],
    tags: [
      'shopping-cart',
      'shopping',
      'cart',
      'store',
      'checkout',
      'buy',
      'panier',
      'caddie',
      'carrito',
      'compras',
      'καλάθι',
      'αγορές',
      'koszyk',
      'zakupy',
    ],
  },
  {
    slug: 'shuffle',
    component: ShuffleIconComponent,
    categories: ['feather'],
    tags: [
      'shuffle',
      'random',
      'mix',
      'media',
      'aléatoire',
      'aleatorio',
      'mezclar',
      'τυχαία',
      'ανακάτεμα',
      'losowo',
      'tasuj',
      'music',
      'audio',
    ],
  },
  {
    slug: 'sidebar',
    component: SidebarIconComponent,
    categories: ['feather'],
    tags: [
      'sidebar',
      'panel',
      'navigation',
      'layout',
      'menu',
      'barre latérale',
      'panneau',
      'barra lateral',
      'panel',
      'πλευρική μπάρα',
      'panel boczny',
    ],
  },
  {
    slug: 'skip-back',
    component: SkipBackIconComponent,
    categories: ['feather'],
    tags: [
      'skip-back',
      'skip',
      'back',
      'previous',
      'media',
      'player',
      'précédent',
      'anterior',
      'προηγούμενο',
      'poprzedni',
      'cofnij',
      'music',
      'audio',
    ],
  },
  {
    slug: 'skip-forward',
    component: SkipForwardIconComponent,
    categories: ['feather'],
    tags: [
      'skip-forward',
      'skip',
      'forward',
      'next',
      'media',
      'player',
      'suivant',
      'siguiente',
      'επόμενο',
      'następny',
      'do przodu',
      'music',
      'audio',
    ],
  },
  {
    slug: 'slack',
    component: SlackIconComponent,
    categories: ['brand'],
    tags: ['slack', 'chat', 'messaging', 'workspace', 'team'],
  },
  {
    slug: 'slash',
    component: SlashIconComponent,
    categories: ['feather'],
    tags: [
      'slash',
      'cancel',
      'forbidden',
      'no',
      'disabled',
      'barre',
      'barra',
      'πλάγια',
      'ukośnik',
      'zakaz',
    ],
  },
  {
    slug: 'sliders',
    component: SlidersIconComponent,
    categories: ['feather'],
    tags: [
      'sliders',
      'controls',
      'settings',
      'adjust',
      'mixer',
      'equalizer',
      'curseurs',
      'réglages',
      'controles',
      'ajustes',
      'ρυθμιστικά',
      'έλεγχοι',
      'suwaki',
      'regulacja',
    ],
  },
  {
    slug: 'smartphone',
    component: SmartphoneIconComponent,
    categories: ['feather'],
    tags: [
      'smartphone',
      'phone',
      'mobile',
      'device',
      'cell',
      'téléphone',
      'móvil',
      'celular',
      'κινητό',
      'συσκευή',
      'smartfon',
      'komórka',
    ],
  },
  {
    slug: 'smile',
    component: SmileIconComponent,
    categories: ['feather'],
    tags: [
      'smile',
      'happy',
      'face',
      'emoji',
      'positive',
      'sourire',
      'visage',
      'sonrisa',
      'feliz',
      'cara',
      'χαμόγελο',
      'χαρούμενος',
      'uśmiech',
      'twarz',
    ],
  },
  {
    slug: 'soccer-ball',
    component: SoccerBallIconComponent,
    categories: ['eagami'],
    tags: [
      'soccer-ball',
      'soccer',
      'ball',
      'football',
      'sport',
      'futbol',
      'fútbol',
      'pelota',
      'ποδόσφαιρο',
      'μπάλα',
      'piłka',
      'nożna',
    ],
  },
  {
    slug: 'speaker',
    component: SpeakerIconComponent,
    categories: ['feather'],
    tags: [
      'speaker',
      'audio',
      'sound',
      'music',
      'volume',
      'haut-parleur',
      'altavoz',
      'sonido',
      'ηχείο',
      'ήχος',
      'głośnik',
      'dźwięk',
    ],
  },
  {
    slug: 'spotify',
    component: SpotifyIconComponent,
    categories: ['brand'],
    tags: ['spotify', 'music', 'streaming', 'audio'],
  },
  {
    slug: 'square',
    component: SquareIconComponent,
    categories: ['feather'],
    tags: [
      'square',
      'shape',
      'box',
      'rectangle',
      'carré',
      'cuadrado',
      'τετράγωνο',
      'σχήμα',
      'kwadrat',
      'kształt',
    ],
  },
  {
    slug: 'star',
    component: StarIconComponent,
    categories: ['feather'],
    tags: [
      'star',
      'favorite',
      'rating',
      'bookmark',
      'like',
      'étoile',
      'favori',
      'estrella',
      'favorito',
      'αστέρι',
      'αγαπημένο',
      'gwiazda',
      'ulubione',
      'shape',
    ],
  },
  {
    slug: 'stop-circle',
    component: StopCircleIconComponent,
    categories: ['feather'],
    tags: [
      'stop-circle',
      'stop',
      'circle',
      'media',
      'player',
      'end',
      'arrêter',
      'detener',
      'parar',
      'σταμάτημα',
      'τέλος',
      'zatrzymaj',
      'stop',
      'music',
      'audio',
    ],
  },
  {
    slug: 'stripe',
    component: StripeIconComponent,
    categories: ['brand'],
    tags: ['stripe', 'payment', 'checkout', 'money'],
  },
  {
    slug: 'sun',
    component: SunIconComponent,
    categories: ['feather'],
    tags: [
      'sun',
      'light',
      'day',
      'theme',
      'weather',
      'soleil',
      'sol',
      'día',
      'ήλιος',
      'φως',
      'słońce',
      'dzień',
    ],
  },
  {
    slug: 'sunrise',
    component: SunriseIconComponent,
    categories: ['feather'],
    tags: [
      'sunrise',
      'sun',
      'morning',
      'dawn',
      'weather',
      'lever du soleil',
      'amanecer',
      'aurora',
      'ανατολή',
      'πρωί',
      'wschód',
      'poranek',
    ],
  },
  {
    slug: 'sunset',
    component: SunsetIconComponent,
    categories: ['feather'],
    tags: [
      'sunset',
      'sun',
      'evening',
      'dusk',
      'weather',
      'coucher du soleil',
      'atardecer',
      'puesta',
      'δύση',
      'σούρουπο',
      'zachód',
      'wieczór',
    ],
  },
  {
    slug: 'tablet',
    component: TabletIconComponent,
    categories: ['feather'],
    tags: [
      'tablet',
      'device',
      'ipad',
      'screen',
      'mobile',
      'tableta',
      'tableta',
      'ταμπλέτα',
      'συσκευή',
      'tablet',
      'urządzenie',
    ],
  },
  {
    slug: 'tag',
    component: TagIconComponent,
    categories: ['feather'],
    tags: [
      'tag',
      'label',
      'price',
      'category',
      'sticker',
      'étiquette',
      'etiqueta',
      'ετικέτα',
      'κατηγορία',
      'etykieta',
      'metka',
    ],
  },
  {
    slug: 'target',
    component: TargetIconComponent,
    categories: ['feather'],
    tags: [
      'target',
      'aim',
      'goal',
      'focus',
      'bullseye',
      'cible',
      'objectif',
      'objetivo',
      'diana',
      'στόχος',
      'σκοπός',
      'cel',
      'tarcza',
    ],
  },
  {
    slug: 'terminal',
    component: TerminalIconComponent,
    categories: ['feather'],
    tags: [
      'terminal',
      'console',
      'command',
      'shell',
      'prompt',
      'developer',
      'terminal',
      'consola',
      'τερματικό',
      'κονσόλα',
      'konsola',
      'wiersz poleceń',
    ],
  },
  {
    slug: 'thermometer',
    component: ThermometerIconComponent,
    categories: ['feather'],
    tags: [
      'thermometer',
      'temperature',
      'weather',
      'hot',
      'cold',
      'thermomètre',
      'température',
      'termómetro',
      'temperatura',
      'θερμόμετρο',
      'θερμοκρασία',
      'termometr',
      'temperatura',
    ],
  },
  {
    slug: 'thumbs-down',
    component: ThumbsDownIconComponent,
    categories: ['feather'],
    tags: [
      'thumbs-down',
      'thumbs',
      'down',
      'dislike',
      'no',
      'negative',
      'pouce',
      'bas',
      'pulgar',
      'abajo',
      'no me gusta',
      'αντίχειρας',
      'κάτω',
      'kciuk',
      'dół',
    ],
  },
  {
    slug: 'thumbs-up',
    component: ThumbsUpIconComponent,
    categories: ['feather'],
    tags: [
      'thumbs-up',
      'thumbs',
      'up',
      'like',
      'yes',
      'approve',
      'positive',
      'pouce',
      'haut',
      'pulgar',
      'arriba',
      'me gusta',
      'αντίχειρας',
      'πάνω',
      'kciuk',
      'góra',
    ],
  },
  {
    slug: 'toggle-left',
    component: ToggleLeftIconComponent,
    categories: ['feather'],
    tags: [
      'toggle-left',
      'toggle',
      'left',
      'switch',
      'off',
      'interrupteur',
      'gauche',
      'interruptor',
      'izquierda',
      'διακόπτης',
      'αριστερά',
      'przełącznik',
      'lewo',
    ],
  },
  {
    slug: 'toggle-right',
    component: ToggleRightIconComponent,
    categories: ['feather'],
    tags: [
      'toggle-right',
      'toggle',
      'right',
      'switch',
      'on',
      'interrupteur',
      'droite',
      'interruptor',
      'derecha',
      'διακόπτης',
      'δεξιά',
      'przełącznik',
      'prawo',
    ],
  },
  {
    slug: 'tool',
    component: ToolIconComponent,
    categories: ['feather'],
    tags: [
      'tool',
      'wrench',
      'fix',
      'repair',
      'settings',
      'outil',
      'clé',
      'herramienta',
      'llave',
      'εργαλείο',
      'κλειδί',
      'narzędzie',
      'klucz',
    ],
  },
  {
    slug: 'trash',
    component: TrashIconComponent,
    categories: ['feather'],
    tags: [
      'trash',
      'delete',
      'remove',
      'bin',
      'garbage',
      'waste',
      'poubelle',
      'supprimer',
      'basura',
      'eliminar',
      'κάδος',
      'διαγραφή',
      'kosz',
      'usuń',
    ],
  },
  {
    slug: 'trash-2',
    component: Trash2IconComponent,
    categories: ['feather'],
    tags: [
      'trash-2',
      'trash',
      '2',
      'delete',
      'remove',
      'bin',
      'garbage',
      'poubelle',
      'basura',
      'eliminar',
      'κάδος',
      'διαγραφή',
      'kosz',
      'usuń',
    ],
  },
  {
    slug: 'trending-down',
    component: TrendingDownIconComponent,
    categories: ['feather'],
    tags: [
      'trending-down',
      'trending',
      'down',
      'decrease',
      'graph',
      'arrow',
      'statistics',
      'tendance',
      'baisse',
      'tendencia',
      'bajada',
      'τάση',
      'κάτω',
      'trend',
      'spadek',
    ],
  },
  {
    slug: 'trending-up',
    component: TrendingUpIconComponent,
    categories: ['feather'],
    tags: [
      'trending-up',
      'trending',
      'up',
      'increase',
      'graph',
      'arrow',
      'statistics',
      'tendance',
      'hausse',
      'tendencia',
      'subida',
      'τάση',
      'πάνω',
      'trend',
      'wzrost',
    ],
  },
  {
    slug: 'triangle',
    component: TriangleIconComponent,
    categories: ['feather'],
    tags: [
      'triangle',
      'shape',
      'arrow',
      'play',
      'three',
      'triangle',
      'triángulo',
      'τρίγωνο',
      'σχήμα',
      'trójkąt',
      'kształt',
    ],
  },
  {
    slug: 'trophy',
    component: TrophyIconComponent,
    categories: ['eagami'],
    tags: [
      'trophy',
      'award',
      'prize',
      'cup',
      'winner',
      'sport',
      'champion',
      'trophée',
      'récompense',
      'trofeo',
      'premio',
      'τρόπαιο',
      'βραβείο',
      'puchar',
      'nagroda',
    ],
  },
  {
    slug: 'truck',
    component: TruckIconComponent,
    categories: ['feather'],
    tags: [
      'truck',
      'delivery',
      'shipping',
      'vehicle',
      'transport',
      'camion',
      'livraison',
      'camión',
      'envío',
      'φορτηγό',
      'παράδοση',
      'ciężarówka',
      'dostawa',
    ],
  },
  {
    slug: 'tv',
    component: TvIconComponent,
    categories: ['feather'],
    tags: [
      'tv',
      'television',
      'screen',
      'display',
      'monitor',
      'télévision',
      'televisión',
      'τηλεόραση',
      'οθόνη',
      'telewizor',
      'telewizja',
    ],
  },
  {
    slug: 'twitch',
    component: TwitchIconComponent,
    categories: ['brand'],
    tags: ['twitch', 'streaming', 'gaming', 'video'],
  },
  {
    slug: 'type',
    component: TypeIconComponent,
    categories: ['feather'],
    tags: [
      'type',
      'text',
      'font',
      'typography',
      'letter',
      'texte',
      'police',
      'fuente',
      'texto',
      'γραμματοσειρά',
      'κείμενο',
      'czcionka',
      'tekst',
    ],
  },
  {
    slug: 'umbrella',
    component: UmbrellaIconComponent,
    categories: ['feather'],
    tags: [
      'umbrella',
      'rain',
      'weather',
      'protection',
      'parapluie',
      'pluie',
      'paraguas',
      'lluvia',
      'ομπρέλα',
      'βροχή',
      'parasol',
      'deszcz',
    ],
  },
  {
    slug: 'underline',
    component: UnderlineIconComponent,
    categories: ['feather'],
    tags: [
      'underline',
      'text',
      'format',
      'style',
      'souligné',
      'subrayado',
      'υπογράμμιση',
      'podkreślenie',
    ],
  },
  {
    slug: 'unlock',
    component: UnlockIconComponent,
    categories: ['feather'],
    tags: [
      'unlock',
      'open',
      'security',
      'access',
      'password',
      'déverrouiller',
      'desbloquear',
      'abierto',
      'ξεκλείδωμα',
      'άνοιγμα',
      'odblokuj',
      'otwórz',
    ],
  },
  {
    slug: 'upload',
    component: UploadIconComponent,
    categories: ['feather'],
    tags: [
      'upload',
      'send',
      'arrow',
      'share',
      'submit',
      'téléverser',
      'envoyer',
      'subir',
      'cargar',
      'μεταφόρτωση',
      'ανέβασμα',
      'prześlij',
      'wgraj',
    ],
  },
  {
    slug: 'upload-cloud',
    component: UploadCloudIconComponent,
    categories: ['feather'],
    tags: [
      'upload-cloud',
      'upload',
      'cloud',
      'send',
      'sync',
      'backup',
      'téléverser',
      'nuage',
      'subir',
      'nube',
      'μεταφόρτωση',
      'σύννεφο',
      'prześlij',
      'chmura',
    ],
  },
  {
    slug: 'user',
    component: UserIconComponent,
    categories: ['feather'],
    tags: [
      'user',
      'person',
      'profile',
      'account',
      'avatar',
      'utilisateur',
      'personne',
      'usuario',
      'persona',
      'χρήστης',
      'άτομο',
      'użytkownik',
      'osoba',
    ],
  },
  {
    slug: 'user-check',
    component: UserCheckIconComponent,
    categories: ['feather'],
    tags: [
      'user-check',
      'user',
      'check',
      'verified',
      'approved',
      'confirm',
      'utilisateur',
      'usuario',
      'verificado',
      'χρήστης',
      'επιβεβαίωση',
      'użytkownik',
      'zatwierdź',
    ],
  },
  {
    slug: 'user-minus',
    component: UserMinusIconComponent,
    categories: ['feather'],
    tags: [
      'user-minus',
      'user',
      'minus',
      'remove',
      'delete',
      'unfollow',
      'utilisateur',
      'usuario',
      'eliminar',
      'χρήστης',
      'αφαίρεση',
      'użytkownik',
      'usuń',
    ],
  },
  {
    slug: 'user-plus',
    component: UserPlusIconComponent,
    categories: ['feather'],
    tags: [
      'user-plus',
      'user',
      'plus',
      'add',
      'new',
      'invite',
      'follow',
      'utilisateur',
      'usuario',
      'añadir',
      'χρήστης',
      'προσθήκη',
      'użytkownik',
      'dodaj',
    ],
  },
  {
    slug: 'user-x',
    component: UserXIconComponent,
    categories: ['feather'],
    tags: [
      'user-x',
      'user',
      'x',
      'remove',
      'delete',
      'block',
      'utilisateur',
      'usuario',
      'bloquear',
      'χρήστης',
      'αποκλεισμός',
      'użytkownik',
      'zablokuj',
    ],
  },
  {
    slug: 'users',
    component: UsersIconComponent,
    categories: ['feather'],
    tags: [
      'users',
      'people',
      'group',
      'team',
      'community',
      'utilisateurs',
      'personnes',
      'usuarios',
      'personas',
      'grupo',
      'χρήστες',
      'άτομα',
      'ομάδα',
      'użytkownicy',
      'grupa',
    ],
  },
  {
    slug: 'vercel',
    component: VercelIconComponent,
    categories: ['brand'],
    tags: ['vercel', 'hosting', 'deploy', 'nextjs'],
  },
  {
    slug: 'video',
    component: VideoIconComponent,
    categories: ['feather'],
    tags: [
      'video',
      'camera',
      'film',
      'movie',
      'record',
      'vidéo',
      'caméra',
      'vídeo',
      'cámara',
      'βίντεο',
      'κάμερα',
      'wideo',
      'kamera',
    ],
  },
  {
    slug: 'video-off',
    component: VideoOffIconComponent,
    categories: ['feather'],
    tags: [
      'video-off',
      'video',
      'off',
      'camera',
      'disabled',
      'mute',
      'vidéo',
      'vídeo',
      'cámara',
      'βίντεο',
      'κάμερα',
      'wideo',
      'wyłączone',
    ],
  },
  {
    slug: 'voicemail',
    component: VoicemailIconComponent,
    categories: ['feather'],
    tags: [
      'voicemail',
      'message',
      'voice',
      'phone',
      'recording',
      'messagerie',
      'buzón',
      'voz',
      'τηλεφωνητής',
      'φωνή',
      'poczta',
      'głosowa',
      'music',
      'audio',
    ],
  },
  {
    slug: 'volume',
    component: VolumeIconComponent,
    categories: ['feather'],
    tags: [
      'volume',
      'sound',
      'audio',
      'speaker',
      'mute',
      'son',
      'sonido',
      'altavoz',
      'ένταση',
      'ήχος',
      'głośność',
      'dźwięk',
      'music',
    ],
  },
  {
    slug: 'volume-1',
    component: Volume1IconComponent,
    categories: ['feather'],
    tags: [
      'volume-1',
      'volume',
      '1',
      'sound',
      'audio',
      'low',
      'son',
      'sonido',
      'ένταση',
      'ήχος',
      'głośność',
      'dźwięk',
      'music',
    ],
  },
  {
    slug: 'volume-2',
    component: Volume2IconComponent,
    categories: ['feather'],
    tags: [
      'volume-2',
      'volume',
      '2',
      'sound',
      'audio',
      'high',
      'son',
      'sonido',
      'ένταση',
      'ήχος',
      'głośność',
      'dźwięk',
      'music',
    ],
  },
  {
    slug: 'volume-x',
    component: VolumeXIconComponent,
    categories: ['feather'],
    tags: [
      'volume-x',
      'volume',
      'x',
      'mute',
      'silent',
      'off',
      'sound',
      'muet',
      'silencio',
      'mudo',
      'σίγαση',
      'wyciszony',
      'cisza',
      'music',
      'audio',
    ],
  },
  {
    slug: 'watch',
    component: WatchIconComponent,
    categories: ['feather'],
    tags: [
      'watch',
      'time',
      'clock',
      'wristwatch',
      'smartwatch',
      'montre',
      'reloj',
      'ρολόι',
      'ώρα',
      'zegarek',
      'czas',
    ],
  },
  {
    slug: 'wifi',
    component: WifiIconComponent,
    categories: ['feather'],
    tags: [
      'wifi',
      'wireless',
      'internet',
      'signal',
      'network',
      'sans-fil',
      'inalámbrico',
      'señal',
      'ασύρματο',
      'σήμα',
      'bezprzewodowy',
      'sygnał',
    ],
  },
  {
    slug: 'wifi-off',
    component: WifiOffIconComponent,
    categories: ['feather'],
    tags: [
      'wifi-off',
      'wifi',
      'off',
      'wireless',
      'disabled',
      'offline',
      'sans-fil',
      'inalámbrico',
      'ασύρματο',
      'εκτός',
      'bezprzewodowy',
      'wyłączone',
    ],
  },
  {
    slug: 'wind',
    component: WindIconComponent,
    categories: ['feather'],
    tags: [
      'wind',
      'air',
      'weather',
      'breeze',
      'storm',
      'vent',
      'viento',
      'aire',
      'άνεμος',
      'αέρας',
      'wiatr',
      'powietrze',
    ],
  },
  {
    slug: 'x',
    component: XIconComponent,
    categories: ['feather'],
    tags: [
      'x',
      'close',
      'cancel',
      'cross',
      'remove',
      'exit',
      'fermer',
      'cerrar',
      'κλείσιμο',
      'άκυρο',
      'zamknij',
      'anuluj',
    ],
  },
  {
    slug: 'x-circle',
    component: XCircleIconComponent,
    categories: ['feather'],
    tags: [
      'x-circle',
      'x',
      'circle',
      'close',
      'cancel',
      'remove',
      'error',
      'fermer',
      'cerrar',
      'cancelar',
      'κλείσιμο',
      'σφάλμα',
      'zamknij',
      'błąd',
    ],
  },
  {
    slug: 'x-octagon',
    component: XOctagonIconComponent,
    categories: ['feather'],
    tags: [
      'x-octagon',
      'x',
      'octagon',
      'close',
      'stop',
      'cancel',
      'error',
      'fermer',
      'detener',
      'κλείσιμο',
      'στοπ',
      'zatrzymaj',
      'błąd',
    ],
  },
  {
    slug: 'x-square',
    component: XSquareIconComponent,
    categories: ['feather'],
    tags: [
      'x-square',
      'x',
      'square',
      'close',
      'cancel',
      'remove',
      'fermer',
      'cerrar',
      'cancelar',
      'κλείσιμο',
      'άκυρο',
      'zamknij',
      'anuluj',
    ],
  },
  {
    slug: 'x-twitter',
    component: XTwitterIconComponent,
    categories: ['brand'],
    tags: ['x-twitter', 'x', 'twitter', 'social', 'tweet'],
  },
  {
    slug: 'youtube',
    component: YoutubeIconComponent,
    categories: ['brand'],
    tags: ['youtube', 'video', 'streaming', 'social'],
  },
  {
    slug: 'zap',
    component: ZapIconComponent,
    categories: ['feather'],
    tags: [
      'zap',
      'lightning',
      'bolt',
      'flash',
      'electric',
      'power',
      'éclair',
      'foudre',
      'rayo',
      'relámpago',
      'αστραπή',
      'κεραυνός',
      'błyskawica',
      'piorun',
    ],
  },
  {
    slug: 'zap-off',
    component: ZapOffIconComponent,
    categories: ['feather'],
    tags: [
      'zap-off',
      'zap',
      'off',
      'lightning',
      'disabled',
      'no power',
      'éclair',
      'rayo',
      'αστραπή',
      'błyskawica',
      'wyłączone',
    ],
  },
  {
    slug: 'zoom-in',
    component: ZoomInIconComponent,
    categories: ['feather'],
    tags: [
      'zoom-in',
      'zoom',
      'in',
      'magnify',
      'enlarge',
      'closer',
      'agrandir',
      'acercar',
      'ampliar',
      'μεγέθυνση',
      'εστίαση',
      'powiększ',
      'przybliż',
    ],
  },
  {
    slug: 'zoom-out',
    component: ZoomOutIconComponent,
    categories: ['feather'],
    tags: [
      'zoom-out',
      'zoom',
      'out',
      'shrink',
      'reduce',
      'farther',
      'réduire',
      'alejar',
      'reducir',
      'σμίκρυνση',
      'απομάκρυνση',
      'pomniejsz',
      'oddal',
    ],
  },
];
