import {
  ActivityIconComponent,
  AirplayIconComponent,
  AlertCircleIconComponent,
  AlertOctagonIconComponent,
  AlertTriangleIconComponent,
  AlignCenterIconComponent,
  AlignJustifyIconComponent,
  AlignLeftIconComponent,
  AlignRightIconComponent,
  AnchorIconComponent,
  ApertureIconComponent,
  ArchiveIconComponent,
  ArrowDownIconComponent,
  ArrowDownLeftIconComponent,
  ArrowDownRightIconComponent,
  ArrowLeftIconComponent,
  ArrowRightIconComponent,
  ArrowUpIconComponent,
  ArrowUpLeftIconComponent,
  ArrowUpRightIconComponent,
  AtSignIconComponent,
  AwardIconComponent,
  BarChartIconComponent,
  BatteryChargingIconComponent,
  BatteryIconComponent,
  BellIconComponent,
  BellOffIconComponent,
  BluetoothIconComponent,
  BoldIconComponent,
  BookIconComponent,
  BookOpenIconComponent,
  BookmarkIconComponent,
  BoxIconComponent,
  BriefcaseIconComponent,
  CalendarIconComponent,
  CameraIconComponent,
  CheckCircleIconComponent,
  CheckIconComponent,
  ChevronDownIconComponent,
  ChevronLeftIconComponent,
  ChevronRightIconComponent,
  ChevronUpIconComponent,
  ChevronsUpDownIconComponent,
  ChromeIconComponent,
  ClipboardIconComponent,
  ClockIconComponent,
  CloudIconComponent,
  CloudflareIconComponent,
  CodeIconComponent,
  CodepenIconComponent,
  CodesandboxIconComponent,
  CoffeeIconComponent,
  ColumnsIconComponent,
  CommandIconComponent,
  CompassIconComponent,
  CopyIconComponent,
  CornerDownLeftIconComponent,
  CornerDownRightIconComponent,
  CornerUpLeftIconComponent,
  CornerUpRightIconComponent,
  CpuIconComponent,
  CreditCardIconComponent,
  CropIconComponent,
  CrosshairIconComponent,
  DatabaseIconComponent,
  DeleteIconComponent,
  DiscIconComponent,
  DiscordIconComponent,
  DivideIconComponent,
  DockerIconComponent,
  DollarSignIconComponent,
  DownloadCloudIconComponent,
  DownloadIconComponent,
  DropboxIconComponent,
  DropletIconComponent,
  EagamiIconComponent,
  Edit2IconComponent,
  Edit3IconComponent,
  EditIconComponent,
  ExternalLinkIconComponent,
  EyeIconComponent,
  EyeOffIconComponent,
  FacebookIconComponent,
  FastForwardIconComponent,
  FeatherIconComponent,
  FigmaIconComponent,
  FileIconComponent,
  FileMinusIconComponent,
  FilePlusIconComponent,
  FileTextIconComponent,
  FilmIconComponent,
  FilterIconComponent,
  FlagIconComponent,
  FolderIconComponent,
  FrownIconComponent,
  GiftIconComponent,
  GitBranchIconComponent,
  GitCommitIconComponent,
  GitMergeIconComponent,
  GitPullRequestIconComponent,
  GithubIconComponent,
  GitlabIconComponent,
  GlobeIconComponent,
  GoogleIconComponent,
  GridIconComponent,
  HardDriveIconComponent,
  HashIconComponent,
  HeadphonesIconComponent,
  HeartIconComponent,
  HelpCircleIconComponent,
  HomeIconComponent,
  ImageIconComponent,
  InboxIconComponent,
  InfoIconComponent,
  ItalicIconComponent,
  KeyIconComponent,
  KubernetesIconComponent,
  LayersIconComponent,
  LayoutIconComponent,
  LifeBuoyIconComponent,
  Link2IconComponent,
  LinkIconComponent,
  LinkedinIconComponent,
  ListIconComponent,
  LoaderIconComponent,
  LockIconComponent,
  LogInIconComponent,
  LogOutIconComponent,
  MailIconComponent,
  MapIconComponent,
  MapPinIconComponent,
  MastercardIconComponent,
  Maximize2IconComponent,
  MaximizeIconComponent,
  MehIconComponent,
  MenuIconComponent,
  MessageCircleIconComponent,
  MessageSquareIconComponent,
  MicIconComponent,
  MicOffIconComponent,
  MicrosoftIconComponent,
  Minimize2IconComponent,
  MinimizeIconComponent,
  MinusCircleIconComponent,
  MinusIconComponent,
  MinusSquareIconComponent,
  MongodbIconComponent,
  MonitorIconComponent,
  MoonIconComponent,
  MoreHorizontalIconComponent,
  MoreVerticalIconComponent,
  MousePointerIconComponent,
  MoveIconComponent,
  MusicIconComponent,
  Navigation2IconComponent,
  NavigationIconComponent,
  NetlifyIconComponent,
  NotionIconComponent,
  NpmIconComponent,
  OctagonIconComponent,
  PackageIconComponent,
  PaperclipIconComponent,
  PauseCircleIconComponent,
  PauseIconComponent,
  PaypalIconComponent,
  PencilIconComponent,
  PercentIconComponent,
  PhoneIconComponent,
  PieChartIconComponent,
  PlayCircleIconComponent,
  PlayIconComponent,
  PlusCircleIconComponent,
  PlusIconComponent,
  PlusSquareIconComponent,
  PocketIconComponent,
  PowerIconComponent,
  PrinterIconComponent,
  RadioIconComponent,
  RedditIconComponent,
  RefreshCwIconComponent,
  RepeatIconComponent,
  RewindIconComponent,
  RotateCcwIconComponent,
  RotateCwIconComponent,
  RssIconComponent,
  SaveIconComponent,
  ScissorsIconComponent,
  SearchIconComponent,
  SendIconComponent,
  ServerIconComponent,
  SettingsIconComponent,
  Share2IconComponent,
  ShareIconComponent,
  ShieldIconComponent,
  ShieldOffIconComponent,
  ShoppingBagIconComponent,
  ShoppingCartIconComponent,
  ShuffleIconComponent,
  SidebarIconComponent,
  SkipBackIconComponent,
  SkipForwardIconComponent,
  SlackIconComponent,
  SlashIconComponent,
  SlidersIconComponent,
  SmartphoneIconComponent,
  SmileIconComponent,
  SpeakerIconComponent,
  SpotifyIconComponent,
  SquareIconComponent,
  StarIconComponent,
  StopCircleIconComponent,
  StripeIconComponent,
  SunIconComponent,
  SunriseIconComponent,
  SunsetIconComponent,
  TabletIconComponent,
  TagIconComponent,
  TargetIconComponent,
  TerminalIconComponent,
  ThermometerIconComponent,
  ThumbsDownIconComponent,
  ThumbsUpIconComponent,
  ToastService,
  ToggleLeftIconComponent,
  ToggleRightIconComponent,
  ToolIconComponent,
  TooltipDirective,
  Trash2IconComponent,
  TrashIconComponent,
  TrendingDownIconComponent,
  TrendingUpIconComponent,
  TriangleIconComponent,
  TruckIconComponent,
  TvIconComponent,
  TwitchIconComponent,
  TypeIconComponent,
  UmbrellaIconComponent,
  UnderlineIconComponent,
  UnlockIconComponent,
  UploadCloudIconComponent,
  UploadIconComponent,
  UserCheckIconComponent,
  UserIconComponent,
  UserMinusIconComponent,
  UserPlusIconComponent,
  UserXIconComponent,
  UsersIconComponent,
  VercelIconComponent,
  VideoIconComponent,
  VideoOffIconComponent,
  VoicemailIconComponent,
  Volume1IconComponent,
  Volume2IconComponent,
  VolumeIconComponent,
  VolumeXIconComponent,
  WatchIconComponent,
  WifiIconComponent,
  WifiOffIconComponent,
  WindIconComponent,
  XCircleIconComponent,
  XIconComponent,
  XOctagonIconComponent,
  XSquareIconComponent,
  XTwitterIconComponent,
  YoutubeIconComponent,
  ZapIconComponent,
  ZapOffIconComponent,
  ZoomInIconComponent,
  ZoomOutIconComponent,
} from '@eagami/ui';

import { NgComponentOutlet } from '@angular/common';
import { ChangeDetectionStrategy, Component, Type, effect, inject } from '@angular/core';

import { WebI18nService } from '@app/i18n/web-i18n.service';
import { MetaAndTitleService } from '@app/services/meta-and-title.service';

interface IconEntry {
  slug: string;
  component: Type<unknown>;
}

@Component({
  selector: 'web-ui-icons-page',
  templateUrl: './ui-icons-page.component.html',
  styleUrl: './ui-icons-page.component.scss',
  imports: [NgComponentOutlet, TooltipDirective],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class UiIconsPageComponent {
  private readonly metaAndTitleService = inject(MetaAndTitleService);
  private readonly toastService = inject(ToastService);
  private readonly i18n = inject(WebI18nService);

  protected readonly messages = this.i18n.messages;

  protected readonly icons: IconEntry[] = [
    { slug: 'activity', component: ActivityIconComponent },
    { slug: 'airplay', component: AirplayIconComponent },
    { slug: 'alert-circle', component: AlertCircleIconComponent },
    { slug: 'alert-octagon', component: AlertOctagonIconComponent },
    { slug: 'alert-triangle', component: AlertTriangleIconComponent },
    { slug: 'align-center', component: AlignCenterIconComponent },
    { slug: 'align-justify', component: AlignJustifyIconComponent },
    { slug: 'align-left', component: AlignLeftIconComponent },
    { slug: 'align-right', component: AlignRightIconComponent },
    { slug: 'anchor', component: AnchorIconComponent },
    { slug: 'aperture', component: ApertureIconComponent },
    { slug: 'archive', component: ArchiveIconComponent },
    { slug: 'arrow-down', component: ArrowDownIconComponent },
    { slug: 'arrow-down-left', component: ArrowDownLeftIconComponent },
    { slug: 'arrow-down-right', component: ArrowDownRightIconComponent },
    { slug: 'arrow-left', component: ArrowLeftIconComponent },
    { slug: 'arrow-right', component: ArrowRightIconComponent },
    { slug: 'arrow-up', component: ArrowUpIconComponent },
    { slug: 'arrow-up-left', component: ArrowUpLeftIconComponent },
    { slug: 'arrow-up-right', component: ArrowUpRightIconComponent },
    { slug: 'at-sign', component: AtSignIconComponent },
    { slug: 'award', component: AwardIconComponent },
    { slug: 'bar-chart', component: BarChartIconComponent },
    { slug: 'battery', component: BatteryIconComponent },
    { slug: 'battery-charging', component: BatteryChargingIconComponent },
    { slug: 'bell', component: BellIconComponent },
    { slug: 'bell-off', component: BellOffIconComponent },
    { slug: 'bluetooth', component: BluetoothIconComponent },
    { slug: 'bold', component: BoldIconComponent },
    { slug: 'book', component: BookIconComponent },
    { slug: 'book-open', component: BookOpenIconComponent },
    { slug: 'bookmark', component: BookmarkIconComponent },
    { slug: 'box', component: BoxIconComponent },
    { slug: 'briefcase', component: BriefcaseIconComponent },
    { slug: 'calendar', component: CalendarIconComponent },
    { slug: 'camera', component: CameraIconComponent },
    { slug: 'check', component: CheckIconComponent },
    { slug: 'check-circle', component: CheckCircleIconComponent },
    { slug: 'chevron-down', component: ChevronDownIconComponent },
    { slug: 'chevron-left', component: ChevronLeftIconComponent },
    { slug: 'chevron-right', component: ChevronRightIconComponent },
    { slug: 'chevron-up', component: ChevronUpIconComponent },
    { slug: 'chevrons-up-down', component: ChevronsUpDownIconComponent },
    { slug: 'chrome', component: ChromeIconComponent },
    { slug: 'clipboard', component: ClipboardIconComponent },
    { slug: 'clock', component: ClockIconComponent },
    { slug: 'cloud', component: CloudIconComponent },
    { slug: 'cloudflare', component: CloudflareIconComponent },
    { slug: 'code', component: CodeIconComponent },
    { slug: 'codepen', component: CodepenIconComponent },
    { slug: 'codesandbox', component: CodesandboxIconComponent },
    { slug: 'coffee', component: CoffeeIconComponent },
    { slug: 'columns', component: ColumnsIconComponent },
    { slug: 'command', component: CommandIconComponent },
    { slug: 'compass', component: CompassIconComponent },
    { slug: 'copy', component: CopyIconComponent },
    { slug: 'corner-down-left', component: CornerDownLeftIconComponent },
    { slug: 'corner-down-right', component: CornerDownRightIconComponent },
    { slug: 'corner-up-left', component: CornerUpLeftIconComponent },
    { slug: 'corner-up-right', component: CornerUpRightIconComponent },
    { slug: 'cpu', component: CpuIconComponent },
    { slug: 'credit-card', component: CreditCardIconComponent },
    { slug: 'crop', component: CropIconComponent },
    { slug: 'crosshair', component: CrosshairIconComponent },
    { slug: 'database', component: DatabaseIconComponent },
    { slug: 'delete', component: DeleteIconComponent },
    { slug: 'disc', component: DiscIconComponent },
    { slug: 'discord', component: DiscordIconComponent },
    { slug: 'divide', component: DivideIconComponent },
    { slug: 'docker', component: DockerIconComponent },
    { slug: 'dollar-sign', component: DollarSignIconComponent },
    { slug: 'download', component: DownloadIconComponent },
    { slug: 'download-cloud', component: DownloadCloudIconComponent },
    { slug: 'dropbox', component: DropboxIconComponent },
    { slug: 'droplet', component: DropletIconComponent },
    { slug: 'eagami', component: EagamiIconComponent },
    { slug: 'edit', component: EditIconComponent },
    { slug: 'edit-2', component: Edit2IconComponent },
    { slug: 'edit-3', component: Edit3IconComponent },
    { slug: 'external-link', component: ExternalLinkIconComponent },
    { slug: 'eye', component: EyeIconComponent },
    { slug: 'eye-off', component: EyeOffIconComponent },
    { slug: 'facebook', component: FacebookIconComponent },
    { slug: 'fast-forward', component: FastForwardIconComponent },
    { slug: 'feather', component: FeatherIconComponent },
    { slug: 'figma', component: FigmaIconComponent },
    { slug: 'file', component: FileIconComponent },
    { slug: 'file-minus', component: FileMinusIconComponent },
    { slug: 'file-plus', component: FilePlusIconComponent },
    { slug: 'file-text', component: FileTextIconComponent },
    { slug: 'film', component: FilmIconComponent },
    { slug: 'filter', component: FilterIconComponent },
    { slug: 'flag', component: FlagIconComponent },
    { slug: 'folder', component: FolderIconComponent },
    { slug: 'frown', component: FrownIconComponent },
    { slug: 'gift', component: GiftIconComponent },
    { slug: 'git-branch', component: GitBranchIconComponent },
    { slug: 'git-commit', component: GitCommitIconComponent },
    { slug: 'git-merge', component: GitMergeIconComponent },
    { slug: 'git-pull-request', component: GitPullRequestIconComponent },
    { slug: 'github', component: GithubIconComponent },
    { slug: 'gitlab', component: GitlabIconComponent },
    { slug: 'globe', component: GlobeIconComponent },
    { slug: 'google', component: GoogleIconComponent },
    { slug: 'grid', component: GridIconComponent },
    { slug: 'hard-drive', component: HardDriveIconComponent },
    { slug: 'hash', component: HashIconComponent },
    { slug: 'headphones', component: HeadphonesIconComponent },
    { slug: 'heart', component: HeartIconComponent },
    { slug: 'help-circle', component: HelpCircleIconComponent },
    { slug: 'home', component: HomeIconComponent },
    { slug: 'image', component: ImageIconComponent },
    { slug: 'inbox', component: InboxIconComponent },
    { slug: 'info', component: InfoIconComponent },
    { slug: 'italic', component: ItalicIconComponent },
    { slug: 'key', component: KeyIconComponent },
    { slug: 'kubernetes', component: KubernetesIconComponent },
    { slug: 'layers', component: LayersIconComponent },
    { slug: 'layout', component: LayoutIconComponent },
    { slug: 'life-buoy', component: LifeBuoyIconComponent },
    { slug: 'link', component: LinkIconComponent },
    { slug: 'link-2', component: Link2IconComponent },
    { slug: 'linkedin', component: LinkedinIconComponent },
    { slug: 'list', component: ListIconComponent },
    { slug: 'loader', component: LoaderIconComponent },
    { slug: 'lock', component: LockIconComponent },
    { slug: 'log-in', component: LogInIconComponent },
    { slug: 'log-out', component: LogOutIconComponent },
    { slug: 'mail', component: MailIconComponent },
    { slug: 'map', component: MapIconComponent },
    { slug: 'map-pin', component: MapPinIconComponent },
    { slug: 'mastercard', component: MastercardIconComponent },
    { slug: 'maximize', component: MaximizeIconComponent },
    { slug: 'maximize-2', component: Maximize2IconComponent },
    { slug: 'meh', component: MehIconComponent },
    { slug: 'menu', component: MenuIconComponent },
    { slug: 'message-circle', component: MessageCircleIconComponent },
    { slug: 'message-square', component: MessageSquareIconComponent },
    { slug: 'mic', component: MicIconComponent },
    { slug: 'mic-off', component: MicOffIconComponent },
    { slug: 'microsoft', component: MicrosoftIconComponent },
    { slug: 'minimize', component: MinimizeIconComponent },
    { slug: 'minimize-2', component: Minimize2IconComponent },
    { slug: 'minus', component: MinusIconComponent },
    { slug: 'minus-circle', component: MinusCircleIconComponent },
    { slug: 'minus-square', component: MinusSquareIconComponent },
    { slug: 'mongodb', component: MongodbIconComponent },
    { slug: 'monitor', component: MonitorIconComponent },
    { slug: 'moon', component: MoonIconComponent },
    { slug: 'more-horizontal', component: MoreHorizontalIconComponent },
    { slug: 'more-vertical', component: MoreVerticalIconComponent },
    { slug: 'mouse-pointer', component: MousePointerIconComponent },
    { slug: 'move', component: MoveIconComponent },
    { slug: 'music', component: MusicIconComponent },
    { slug: 'navigation', component: NavigationIconComponent },
    { slug: 'navigation-2', component: Navigation2IconComponent },
    { slug: 'netlify', component: NetlifyIconComponent },
    { slug: 'notion', component: NotionIconComponent },
    { slug: 'npm', component: NpmIconComponent },
    { slug: 'octagon', component: OctagonIconComponent },
    { slug: 'package', component: PackageIconComponent },
    { slug: 'paperclip', component: PaperclipIconComponent },
    { slug: 'pause', component: PauseIconComponent },
    { slug: 'pause-circle', component: PauseCircleIconComponent },
    { slug: 'paypal', component: PaypalIconComponent },
    { slug: 'pencil', component: PencilIconComponent },
    { slug: 'percent', component: PercentIconComponent },
    { slug: 'phone', component: PhoneIconComponent },
    { slug: 'pie-chart', component: PieChartIconComponent },
    { slug: 'play', component: PlayIconComponent },
    { slug: 'play-circle', component: PlayCircleIconComponent },
    { slug: 'plus', component: PlusIconComponent },
    { slug: 'plus-circle', component: PlusCircleIconComponent },
    { slug: 'plus-square', component: PlusSquareIconComponent },
    { slug: 'pocket', component: PocketIconComponent },
    { slug: 'power', component: PowerIconComponent },
    { slug: 'printer', component: PrinterIconComponent },
    { slug: 'radio', component: RadioIconComponent },
    { slug: 'reddit', component: RedditIconComponent },
    { slug: 'refresh-cw', component: RefreshCwIconComponent },
    { slug: 'repeat', component: RepeatIconComponent },
    { slug: 'rewind', component: RewindIconComponent },
    { slug: 'rotate-ccw', component: RotateCcwIconComponent },
    { slug: 'rotate-cw', component: RotateCwIconComponent },
    { slug: 'rss', component: RssIconComponent },
    { slug: 'save', component: SaveIconComponent },
    { slug: 'scissors', component: ScissorsIconComponent },
    { slug: 'search', component: SearchIconComponent },
    { slug: 'send', component: SendIconComponent },
    { slug: 'server', component: ServerIconComponent },
    { slug: 'settings', component: SettingsIconComponent },
    { slug: 'share', component: ShareIconComponent },
    { slug: 'share-2', component: Share2IconComponent },
    { slug: 'shield', component: ShieldIconComponent },
    { slug: 'shield-off', component: ShieldOffIconComponent },
    { slug: 'shopping-bag', component: ShoppingBagIconComponent },
    { slug: 'shopping-cart', component: ShoppingCartIconComponent },
    { slug: 'shuffle', component: ShuffleIconComponent },
    { slug: 'sidebar', component: SidebarIconComponent },
    { slug: 'skip-back', component: SkipBackIconComponent },
    { slug: 'skip-forward', component: SkipForwardIconComponent },
    { slug: 'slack', component: SlackIconComponent },
    { slug: 'slash', component: SlashIconComponent },
    { slug: 'sliders', component: SlidersIconComponent },
    { slug: 'smartphone', component: SmartphoneIconComponent },
    { slug: 'smile', component: SmileIconComponent },
    { slug: 'speaker', component: SpeakerIconComponent },
    { slug: 'spotify', component: SpotifyIconComponent },
    { slug: 'square', component: SquareIconComponent },
    { slug: 'star', component: StarIconComponent },
    { slug: 'stop-circle', component: StopCircleIconComponent },
    { slug: 'stripe', component: StripeIconComponent },
    { slug: 'sun', component: SunIconComponent },
    { slug: 'sunrise', component: SunriseIconComponent },
    { slug: 'sunset', component: SunsetIconComponent },
    { slug: 'tablet', component: TabletIconComponent },
    { slug: 'tag', component: TagIconComponent },
    { slug: 'target', component: TargetIconComponent },
    { slug: 'terminal', component: TerminalIconComponent },
    { slug: 'thermometer', component: ThermometerIconComponent },
    { slug: 'thumbs-down', component: ThumbsDownIconComponent },
    { slug: 'thumbs-up', component: ThumbsUpIconComponent },
    { slug: 'toggle-left', component: ToggleLeftIconComponent },
    { slug: 'toggle-right', component: ToggleRightIconComponent },
    { slug: 'tool', component: ToolIconComponent },
    { slug: 'trash', component: TrashIconComponent },
    { slug: 'trash-2', component: Trash2IconComponent },
    { slug: 'trending-down', component: TrendingDownIconComponent },
    { slug: 'trending-up', component: TrendingUpIconComponent },
    { slug: 'triangle', component: TriangleIconComponent },
    { slug: 'truck', component: TruckIconComponent },
    { slug: 'tv', component: TvIconComponent },
    { slug: 'twitch', component: TwitchIconComponent },
    { slug: 'type', component: TypeIconComponent },
    { slug: 'umbrella', component: UmbrellaIconComponent },
    { slug: 'underline', component: UnderlineIconComponent },
    { slug: 'unlock', component: UnlockIconComponent },
    { slug: 'upload', component: UploadIconComponent },
    { slug: 'upload-cloud', component: UploadCloudIconComponent },
    { slug: 'user', component: UserIconComponent },
    { slug: 'user-check', component: UserCheckIconComponent },
    { slug: 'user-minus', component: UserMinusIconComponent },
    { slug: 'user-plus', component: UserPlusIconComponent },
    { slug: 'user-x', component: UserXIconComponent },
    { slug: 'users', component: UsersIconComponent },
    { slug: 'vercel', component: VercelIconComponent },
    { slug: 'video', component: VideoIconComponent },
    { slug: 'video-off', component: VideoOffIconComponent },
    { slug: 'voicemail', component: VoicemailIconComponent },
    { slug: 'volume', component: VolumeIconComponent },
    { slug: 'volume-1', component: Volume1IconComponent },
    { slug: 'volume-2', component: Volume2IconComponent },
    { slug: 'volume-x', component: VolumeXIconComponent },
    { slug: 'watch', component: WatchIconComponent },
    { slug: 'wifi', component: WifiIconComponent },
    { slug: 'wifi-off', component: WifiOffIconComponent },
    { slug: 'wind', component: WindIconComponent },
    { slug: 'x', component: XIconComponent },
    { slug: 'x-circle', component: XCircleIconComponent },
    { slug: 'x-octagon', component: XOctagonIconComponent },
    { slug: 'x-square', component: XSquareIconComponent },
    { slug: 'x-twitter', component: XTwitterIconComponent },
    { slug: 'youtube', component: YoutubeIconComponent },
    { slug: 'zap', component: ZapIconComponent },
    { slug: 'zap-off', component: ZapOffIconComponent },
    { slug: 'zoom-in', component: ZoomInIconComponent },
    { slug: 'zoom-out', component: ZoomOutIconComponent },
  ];

  constructor() {
    effect(() => {
      const m = this.messages().ui.icons;
      this.metaAndTitleService.updateTitle(m.metaTitle);
      this.metaAndTitleService.updateDescription(m.metaDescription);
    });
  }

  protected toTitleCase(slug: string): string {
    return slug
      .split('-')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
  }

  protected async copySelector(slug: string): Promise<void> {
    const selector = `ea-icon-${slug}`;
    const m = this.messages().ui.icons;
    try {
      await navigator.clipboard.writeText(selector);
      this.toastService.show(m.copiedToast(selector), { variant: 'success' });
    } catch {
      this.toastService.show(m.copyFailedToast(selector), { variant: 'error' });
    }
  }
}
