import {
  AlertCircleIconComponent,
  AlertTriangleIconComponent,
  ArchiveIconComponent,
  ArrowDownIconComponent,
  ArrowLeftIconComponent,
  ArrowRightIconComponent,
  ArrowUpIconComponent,
  AtSignIconComponent,
  BarChartIconComponent,
  BellIconComponent,
  BookmarkIconComponent,
  BriefcaseIconComponent,
  CalendarIconComponent,
  CameraIconComponent,
  CheckCircleIconComponent,
  CheckIconComponent,
  ChevronDownIconComponent,
  ChevronLeftIconComponent,
  ChevronRightIconComponent,
  ChevronUpIconComponent,
  ChevronsUpDownIconComponent,
  ClipboardIconComponent,
  ClockIconComponent,
  CloudIconComponent,
  CopyIconComponent,
  CreditCardIconComponent,
  DollarSignIconComponent,
  DownloadIconComponent,
  EagamiIconComponent,
  ExternalLinkIconComponent,
  EyeIconComponent,
  EyeOffIconComponent,
  FacebookIconComponent,
  FileIconComponent,
  FilterIconComponent,
  FlagIconComponent,
  FolderIconComponent,
  GiftIconComponent,
  GithubIconComponent,
  GlobeIconComponent,
  GoogleIconComponent,
  HashIconComponent,
  HeartIconComponent,
  HelpCircleIconComponent,
  HomeIconComponent,
  ImageIconComponent,
  InboxIconComponent,
  InfoIconComponent,
  LinkIconComponent,
  ListIconComponent,
  LoaderIconComponent,
  LockIconComponent,
  LogInIconComponent,
  LogOutIconComponent,
  MailIconComponent,
  MapPinIconComponent,
  MaximizeIconComponent,
  MenuIconComponent,
  MicIconComponent,
  MicrosoftIconComponent,
  MinimizeIconComponent,
  MinusIconComponent,
  MonitorIconComponent,
  MoonIconComponent,
  MoreHorizontalIconComponent,
  PackageIconComponent,
  PaperclipIconComponent,
  PauseIconComponent,
  PencilIconComponent,
  PhoneIconComponent,
  PlayIconComponent,
  PlusIconComponent,
  PrinterIconComponent,
  RefreshCwIconComponent,
  RotateCcwIconComponent,
  SaveIconComponent,
  SearchIconComponent,
  SendIconComponent,
  SettingsIconComponent,
  ShareIconComponent,
  ShieldIconComponent,
  ShoppingCartIconComponent,
  SmartphoneIconComponent,
  StarIconComponent,
  SunIconComponent,
  ThumbsDownIconComponent,
  ThumbsUpIconComponent,
  ToastService,
  TooltipDirective,
  TrashIconComponent,
  TrendingUpIconComponent,
  UnlockIconComponent,
  UploadIconComponent,
  UserIconComponent,
  UsersIconComponent,
  VideoIconComponent,
  Volume2IconComponent,
  WifiIconComponent,
  XCircleIconComponent,
  XIconComponent,
  XTwitterIconComponent,
  ZapIconComponent,
} from '@eagami/ui';

import { NgComponentOutlet } from '@angular/common';
import { ChangeDetectionStrategy, Component, OnInit, Type, inject } from '@angular/core';

import { MetaAndTitleService } from '@app/services/meta-and-title.service';

interface IconEntry {
  slug: string;
  component: Type<unknown>;
}

@Component({
  selector: 'web-ui-icons-page',
  templateUrl: './ui-icons-page.component.html',
  styleUrl: './ui-icons-page.component.scss',
  imports: [NgComponentOutlet, TooltipDirective],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class UiIconsPageComponent implements OnInit {
  private readonly metaAndTitleService = inject(MetaAndTitleService);
  private readonly toastService = inject(ToastService);

  protected readonly icons: IconEntry[] = [
    { slug: 'alert-circle', component: AlertCircleIconComponent },
    { slug: 'alert-triangle', component: AlertTriangleIconComponent },
    { slug: 'archive', component: ArchiveIconComponent },
    { slug: 'arrow-down', component: ArrowDownIconComponent },
    { slug: 'arrow-left', component: ArrowLeftIconComponent },
    { slug: 'arrow-right', component: ArrowRightIconComponent },
    { slug: 'arrow-up', component: ArrowUpIconComponent },
    { slug: 'at-sign', component: AtSignIconComponent },
    { slug: 'bar-chart', component: BarChartIconComponent },
    { slug: 'bell', component: BellIconComponent },
    { slug: 'bookmark', component: BookmarkIconComponent },
    { slug: 'briefcase', component: BriefcaseIconComponent },
    { slug: 'calendar', component: CalendarIconComponent },
    { slug: 'camera', component: CameraIconComponent },
    { slug: 'check', component: CheckIconComponent },
    { slug: 'check-circle', component: CheckCircleIconComponent },
    { slug: 'chevron-down', component: ChevronDownIconComponent },
    { slug: 'chevron-left', component: ChevronLeftIconComponent },
    { slug: 'chevron-right', component: ChevronRightIconComponent },
    { slug: 'chevron-up', component: ChevronUpIconComponent },
    { slug: 'chevrons-up-down', component: ChevronsUpDownIconComponent },
    { slug: 'clipboard', component: ClipboardIconComponent },
    { slug: 'clock', component: ClockIconComponent },
    { slug: 'cloud', component: CloudIconComponent },
    { slug: 'copy', component: CopyIconComponent },
    { slug: 'credit-card', component: CreditCardIconComponent },
    { slug: 'dollar-sign', component: DollarSignIconComponent },
    { slug: 'download', component: DownloadIconComponent },
    { slug: 'eagami', component: EagamiIconComponent },
    { slug: 'external-link', component: ExternalLinkIconComponent },
    { slug: 'eye', component: EyeIconComponent },
    { slug: 'eye-off', component: EyeOffIconComponent },
    { slug: 'facebook', component: FacebookIconComponent },
    { slug: 'file', component: FileIconComponent },
    { slug: 'filter', component: FilterIconComponent },
    { slug: 'flag', component: FlagIconComponent },
    { slug: 'folder', component: FolderIconComponent },
    { slug: 'gift', component: GiftIconComponent },
    { slug: 'github', component: GithubIconComponent },
    { slug: 'globe', component: GlobeIconComponent },
    { slug: 'google', component: GoogleIconComponent },
    { slug: 'hash', component: HashIconComponent },
    { slug: 'heart', component: HeartIconComponent },
    { slug: 'help-circle', component: HelpCircleIconComponent },
    { slug: 'home', component: HomeIconComponent },
    { slug: 'image', component: ImageIconComponent },
    { slug: 'inbox', component: InboxIconComponent },
    { slug: 'info', component: InfoIconComponent },
    { slug: 'link', component: LinkIconComponent },
    { slug: 'list', component: ListIconComponent },
    { slug: 'loader', component: LoaderIconComponent },
    { slug: 'lock', component: LockIconComponent },
    { slug: 'log-in', component: LogInIconComponent },
    { slug: 'log-out', component: LogOutIconComponent },
    { slug: 'mail', component: MailIconComponent },
    { slug: 'map-pin', component: MapPinIconComponent },
    { slug: 'maximize', component: MaximizeIconComponent },
    { slug: 'menu', component: MenuIconComponent },
    { slug: 'mic', component: MicIconComponent },
    { slug: 'microsoft', component: MicrosoftIconComponent },
    { slug: 'minimize', component: MinimizeIconComponent },
    { slug: 'minus', component: MinusIconComponent },
    { slug: 'monitor', component: MonitorIconComponent },
    { slug: 'moon', component: MoonIconComponent },
    { slug: 'more-horizontal', component: MoreHorizontalIconComponent },
    { slug: 'package', component: PackageIconComponent },
    { slug: 'paperclip', component: PaperclipIconComponent },
    { slug: 'pause', component: PauseIconComponent },
    { slug: 'pencil', component: PencilIconComponent },
    { slug: 'phone', component: PhoneIconComponent },
    { slug: 'play', component: PlayIconComponent },
    { slug: 'plus', component: PlusIconComponent },
    { slug: 'printer', component: PrinterIconComponent },
    { slug: 'refresh-cw', component: RefreshCwIconComponent },
    { slug: 'rotate-ccw', component: RotateCcwIconComponent },
    { slug: 'save', component: SaveIconComponent },
    { slug: 'search', component: SearchIconComponent },
    { slug: 'send', component: SendIconComponent },
    { slug: 'settings', component: SettingsIconComponent },
    { slug: 'share', component: ShareIconComponent },
    { slug: 'shield', component: ShieldIconComponent },
    { slug: 'shopping-cart', component: ShoppingCartIconComponent },
    { slug: 'smartphone', component: SmartphoneIconComponent },
    { slug: 'star', component: StarIconComponent },
    { slug: 'sun', component: SunIconComponent },
    { slug: 'thumbs-down', component: ThumbsDownIconComponent },
    { slug: 'thumbs-up', component: ThumbsUpIconComponent },
    { slug: 'trash', component: TrashIconComponent },
    { slug: 'trending-up', component: TrendingUpIconComponent },
    { slug: 'unlock', component: UnlockIconComponent },
    { slug: 'upload', component: UploadIconComponent },
    { slug: 'user', component: UserIconComponent },
    { slug: 'users', component: UsersIconComponent },
    { slug: 'video', component: VideoIconComponent },
    { slug: 'volume-2', component: Volume2IconComponent },
    { slug: 'wifi', component: WifiIconComponent },
    { slug: 'x', component: XIconComponent },
    { slug: 'x-circle', component: XCircleIconComponent },
    { slug: 'x-twitter', component: XTwitterIconComponent },
    { slug: 'zap', component: ZapIconComponent },
  ];

  public ngOnInit(): void {
    this.metaAndTitleService.updateTitle('Eagami | UI');
    this.metaAndTitleService.updateDescription('Icon set bundled with @eagami/ui.');
  }

  protected toTitleCase(slug: string): string {
    return slug
      .split('-')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
  }

  protected async copySelector(slug: string): Promise<void> {
    const selector = `ea-icon-${slug}`;
    try {
      await navigator.clipboard.writeText(selector);
      this.toastService.show(`Copied "${selector}" to clipboard`, {
        variant: 'success',
      });
    } catch {
      this.toastService.show(`Could not copy "${selector}" to clipboard`, {
        variant: 'error',
      });
    }
  }
}
